// ignore_for_file: non_constant_identifier_names

import 'timeago_symbol.dart';

final _en = TimeagoSymbol(
  JUST_NOW: (SHORT: 'now', LONG: 'just now'),
  SECONDS: (SHORT: 's', LONG: 'seconds'),
  ONE_MINUTE: (SHORT: '1m', LONG: 'a minute'),
  MINUTES: (SHORT: 'm', LONG: 'minutes'),
  ONE_HOUR: (SHORT: '1h', LONG: 'an hour'),
  HOURS: (SHORT: 'h', LONG: 'hours'),
  ONE_DAY: (SHORT: '1d', LONG: 'a day'),
  DAYS: (SHORT: 'd', LONG: 'days'),
  ONE_MONTH: (SHORT: '1mo', LONG: 'a month'),
  MONTHS: (SHORT: 'mo', LONG: 'months'),
  SUFFIX: (SHORT: 'ago', LONG: 'ago'),
  ONE_YEAR: (SHORT: '1yr', LONG: 'a year'),
  YEARS: (SHORT: 'yr', LONG: 'years'),
  SEPARATOR: (SHORT: '', LONG: ' '),
);

Map<String, TimeagoSymbol> timeagoSymbolMap() {
  return {
    'en': _en,
    'en_ISO': _en,
    'en_AU': _en,
    'en_CA': _en,
    'en_GB': _en,
    'en_IE': _en,
    'en_IN': _en,
    'en_MY': _en,
    'en_NZ': _en,
    'en_SG': _en,
    'en_US': _en,
    'en_ZA': _en,
    'af': TimeagoSymbol(
      JUST_NOW: (SHORT: 'nou', LONG: 'nou net'),
      SECONDS: (SHORT: 's', LONG: 'sekondes'),
      ONE_MINUTE: (SHORT: 'm', LONG: '’n minuut'),
      MINUTES: (SHORT: 'm', LONG: 'minute'),
      ONE_HOUR: (SHORT: 'h', LONG: '’n uur'),
      HOURS: (SHORT: 'h', LONG: 'ure'),
      ONE_DAY: (SHORT: 'd', LONG: '’n dag'),
      DAYS: (SHORT: 'd', LONG: 'dae'),
      ONE_MONTH: (SHORT: 'm', LONG: '’n maand'),
      MONTHS: (SHORT: 'm', LONG: 'maande'),
      SUFFIX: (SHORT: 'gelede', LONG: 'gelede'),
      ONE_YEAR: (SHORT: 'j', LONG: '’n jaar'),
      YEARS: (SHORT: 'j', LONG: 'jare'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'am': TimeagoSymbol(
      JUST_NOW: (SHORT: 'አሁን', LONG: 'አሁን በላይ'),
      SECONDS: (SHORT: 'ሰ', LONG: 'ሰከንዶች'),
      ONE_MINUTE: (SHORT: 'ደ', LONG: 'አንድ ደብቆች'),
      MINUTES: (SHORT: 'ደ', LONG: 'ደብቆች'),
      ONE_HOUR: (SHORT: 'ሰ', LONG: 'አንድ ሰዓት'),
      HOURS: (SHORT: 'ሰ', LONG: 'ሰዓቶች'),
      ONE_DAY: (SHORT: 'ቀ', LONG: 'አንድ ቀን'),
      DAYS: (SHORT: 'ቀ', LONG: 'ቀናቶች'),
      ONE_MONTH: (SHORT: 'ወ', LONG: 'አንድ ወር'),
      MONTHS: (SHORT: 'ወ', LONG: 'ወራቶች'),
      SUFFIX: (SHORT: 'በፊት', LONG: 'በፊት'),
      ONE_YEAR: (SHORT: 'ዓ', LONG: 'አንድ ዓመት'),
      YEARS: (SHORT: 'ዓ', LONG: 'ዓመታት'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'ar': TimeagoSymbol(
      JUST_NOW: (SHORT: 'الآن', LONG: 'الآن'),
      SECONDS: (SHORT: 'ث', LONG: 'ثواني'),
      ONE_MINUTE: (SHORT: 'د', LONG: 'دقيقة'),
      MINUTES: (SHORT: 'د', LONG: 'دقائق'),
      ONE_HOUR: (SHORT: 'س', LONG: 'ساعة'),
      HOURS: (SHORT: 'س', LONG: 'ساعات'),
      ONE_DAY: (SHORT: 'ي', LONG: 'يوم'),
      DAYS: (SHORT: 'ي', LONG: 'أيام'),
      ONE_MONTH: (SHORT: 'ش', LONG: 'شهر'),
      MONTHS: (SHORT: 'ش', LONG: 'أشهر'),
      SUFFIX: (SHORT: 'منذ', LONG: 'منذ'),
      ONE_YEAR: (SHORT: 'س', LONG: 'سنة'),
      YEARS: (SHORT: 'س', LONG: 'سنوات'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'ar_DZ': TimeagoSymbol(
      JUST_NOW: (SHORT: 'الآن', LONG: 'الآن'),
      SECONDS: (SHORT: 'ث', LONG: 'ثواني'),
      ONE_MINUTE: (SHORT: 'د', LONG: 'دقيقة'),
      MINUTES: (SHORT: 'د', LONG: 'دقائق'),
      ONE_HOUR: (SHORT: 'س', LONG: 'ساعة'),
      HOURS: (SHORT: 'س', LONG: 'ساعات'),
      ONE_DAY: (SHORT: 'ي', LONG: 'يوم'),
      DAYS: (SHORT: 'ي', LONG: 'أيام'),
      ONE_MONTH: (SHORT: 'ش', LONG: 'شهر'),
      MONTHS: (SHORT: 'ش', LONG: 'أشهر'),
      SUFFIX: (SHORT: 'منذ', LONG: 'منذ'),
      ONE_YEAR: (SHORT: 'س', LONG: 'سنة'),
      YEARS: (SHORT: 'س', LONG: 'سنوات'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'ar_EG': TimeagoSymbol(
      JUST_NOW: (SHORT: 'الآن', LONG: 'الآن'),
      SECONDS: (SHORT: 'ث', LONG: 'ثواني'),
      ONE_MINUTE: (SHORT: 'د', LONG: 'دقيقة'),
      MINUTES: (SHORT: 'د', LONG: 'دقائق'),
      ONE_HOUR: (SHORT: 'س', LONG: 'ساعة'),
      HOURS: (SHORT: 'س', LONG: 'ساعات'),
      ONE_DAY: (SHORT: 'ي', LONG: 'يوم'),
      DAYS: (SHORT: 'ي', LONG: 'أيام'),
      ONE_MONTH: (SHORT: 'ش', LONG: 'شهر'),
      MONTHS: (SHORT: 'ش', LONG: 'أشهر'),
      SUFFIX: (SHORT: 'منذ', LONG: 'منذ'),
      ONE_YEAR: (SHORT: 'س', LONG: 'سنة'),
      YEARS: (SHORT: 'س', LONG: 'سنوات'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'as': TimeagoSymbol(
      JUST_NOW: (SHORT: 'এতিয়া', LONG: 'এতিয়াকে'),
      SECONDS: (SHORT: 'ছ', LONG: 'ছেকেণ্ড'),
      ONE_MINUTE: (SHORT: 'মিনিট', LONG: 'এটা এটি মিনিট'),
      MINUTES: (SHORT: 'মিনিট', LONG: 'মিনিট'),
      ONE_HOUR: (SHORT: 'ঘণ্টা', LONG: 'এটা এটি ঘণ্টা'),
      HOURS: (SHORT: 'ঘণ্টা', LONG: 'ঘণ্টা'),
      ONE_DAY: (SHORT: 'দিন', LONG: 'এটা এটি দিন'),
      DAYS: (SHORT: 'দিন', LONG: 'দিন'),
      ONE_MONTH: (SHORT: 'মাহ', LONG: 'এটা এটি মাহ'),
      MONTHS: (SHORT: 'মাহ', LONG: 'মাহ'),
      SUFFIX: (SHORT: 'পৰা', LONG: 'পৰা'),
      ONE_YEAR: (SHORT: 'বছৰ', LONG: 'এটা এটি বছৰ'),
      YEARS: (SHORT: 'বছৰ', LONG: 'বছৰ'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'az': TimeagoSymbol(
      JUST_NOW: (SHORT: 'indi', LONG: 'indi'),
      SECONDS: (SHORT: 's', LONG: 'saniyə'),
      ONE_MINUTE: (SHORT: 'd', LONG: 'bir dəqiqə'),
      MINUTES: (SHORT: 'd', LONG: 'dəqiqə'),
      ONE_HOUR: (SHORT: 's', LONG: 'bir saat'),
      HOURS: (SHORT: 's', LONG: 'saat'),
      ONE_DAY: (SHORT: 'g', LONG: 'bir gün'),
      DAYS: (SHORT: 'g', LONG: 'gün'),
      ONE_MONTH: (SHORT: 'a', LONG: 'bir ay'),
      MONTHS: (SHORT: 'a', LONG: 'ay'),
      SUFFIX: (SHORT: 'əvvəl', LONG: 'əvvəl'),
      ONE_YEAR: (SHORT: 'i', LONG: 'bir il'),
      YEARS: (SHORT: 'i', LONG: 'il'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'be': TimeagoSymbol(
      JUST_NOW: (SHORT: 'цяпер', LONG: 'цяпер'),
      SECONDS: (SHORT: 'с', LONG: 'секунда'),
      ONE_MINUTE: (SHORT: 'х', LONG: 'хвіліна'),
      MINUTES: (SHORT: 'х', LONG: 'хвіліны'),
      ONE_HOUR: (SHORT: 'г', LONG: 'гадзіна'),
      HOURS: (SHORT: 'г', LONG: 'гадзіны'),
      ONE_DAY: (SHORT: 'д', LONG: 'дзень'),
      DAYS: (SHORT: 'д', LONG: 'дні'),
      ONE_MONTH: (SHORT: 'м', LONG: 'месяц'),
      MONTHS: (SHORT: 'м', LONG: 'месяцы'),
      SUFFIX: (SHORT: 'таму', LONG: 'таму'),
      ONE_YEAR: (SHORT: 'г', LONG: 'год'),
      YEARS: (SHORT: 'г', LONG: 'гады'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'bg': TimeagoSymbol(
      JUST_NOW: (SHORT: 'сега', LONG: 'точно сега'),
      SECONDS: (SHORT: 'с', LONG: 'секунда'),
      ONE_MINUTE: (SHORT: 'м', LONG: 'минута'),
      MINUTES: (SHORT: 'м', LONG: 'минути'),
      ONE_HOUR: (SHORT: 'ч', LONG: 'час'),
      HOURS: (SHORT: 'ч', LONG: 'часа'),
      ONE_DAY: (SHORT: 'д', LONG: 'ден'),
      DAYS: (SHORT: 'д', LONG: 'дни'),
      ONE_MONTH: (SHORT: 'м', LONG: 'месец'),
      MONTHS: (SHORT: 'м', LONG: 'месеца'),
      SUFFIX: (SHORT: 'преди', LONG: 'преди'),
      ONE_YEAR: (SHORT: 'г', LONG: 'година'),
      YEARS: (SHORT: 'г', LONG: 'години'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'bm': TimeagoSymbol(
      JUST_NOW: (SHORT: 'kɔnɔ', LONG: 'kɔnɔ kɛlɛ'),
      SECONDS: (SHORT: 's', LONG: 'sekondi'),
      ONE_MINUTE: (SHORT: 'm', LONG: 'kɛlɛ miniti'),
      MINUTES: (SHORT: 'm', LONG: 'miniti'),
      ONE_HOUR: (SHORT: 'h', LONG: 'kɛlɛ lɔɔre'),
      HOURS: (SHORT: 'h', LONG: 'lɔɔre'),
      ONE_DAY: (SHORT: 'j', LONG: 'kɛlɛ sabu'),
      DAYS: (SHORT: 'j', LONG: 'sabu'),
      ONE_MONTH: (SHORT: 'm', LONG: 'kɛlɛ kalo'),
      MONTHS: (SHORT: 'm', LONG: 'kalo'),
      SUFFIX: (SHORT: 'ɲɔɔn', LONG: 'ɲɔɔn'),
      ONE_YEAR: (SHORT: 's', LONG: 'kɛlɛ san'),
      YEARS: (SHORT: 's', LONG: 'san'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'bn': TimeagoSymbol(
      JUST_NOW: (SHORT: 'এখন', LONG: 'এখন'),
      SECONDS: (SHORT: 'সেকেন্ড', LONG: 'সেকেন্ড'),
      ONE_MINUTE: (SHORT: 'মিনিট', LONG: 'এক মিনিট'),
      MINUTES: (SHORT: 'মিনিট', LONG: 'মিনিট'),
      ONE_HOUR: (SHORT: 'ঘন্টা', LONG: 'এক ঘন্টা'),
      HOURS: (SHORT: 'ঘন্টা', LONG: 'ঘন্টা'),
      ONE_DAY: (SHORT: 'দিন', LONG: 'এক দিন'),
      DAYS: (SHORT: 'দিন', LONG: 'দিন'),
      ONE_MONTH: (SHORT: 'মাস', LONG: 'এক মাস'),
      MONTHS: (SHORT: 'মাস', LONG: 'মাস'),
      SUFFIX: (SHORT: 'আগে', LONG: 'আগে'),
      ONE_YEAR: (SHORT: 'বছর', LONG: 'এক বছর'),
      YEARS: (SHORT: 'বছর', LONG: 'বছর'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'br': TimeagoSymbol(
      JUST_NOW: (SHORT: 'bremañ', LONG: 'bremañ'),
      SECONDS: (SHORT: 's', LONG: 'eilenn'),
      ONE_MINUTE: (SHORT: 'm', LONG: 'ur vunutenn'),
      MINUTES: (SHORT: 'm', LONG: 'vunutenn'),
      ONE_HOUR: (SHORT: 'e', LONG: 'un eur'),
      HOURS: (SHORT: 'e', LONG: 'eurioù'),
      ONE_DAY: (SHORT: 'j', LONG: 'un devezh'),
      DAYS: (SHORT: 'j', LONG: 'devezhioù'),
      ONE_MONTH: (SHORT: 'm', LONG: 'ur miz'),
      MONTHS: (SHORT: 'm', LONG: 'mizioù'),
      SUFFIX: (SHORT: 'zo', LONG: 'zo'),
      ONE_YEAR: (SHORT: 'b', LONG: 'ur bloaz'),
      YEARS: (SHORT: 'b', LONG: 'bloazioù'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'bs': TimeagoSymbol(
      JUST_NOW: (SHORT: 'sada', LONG: 'sada'),
      SECONDS: (SHORT: 's', LONG: 'sekundi'),
      ONE_MINUTE: (SHORT: 'm', LONG: 'jedan minut'),
      MINUTES: (SHORT: 'm', LONG: 'minute'),
      ONE_HOUR: (SHORT: 's', LONG: 'jedan sat'),
      HOURS: (SHORT: 's', LONG: 'sati'),
      ONE_DAY: (SHORT: 'd', LONG: 'jedan dan'),
      DAYS: (SHORT: 'd', LONG: 'dani'),
      ONE_MONTH: (SHORT: 'm', LONG: 'jedan mjesec'),
      MONTHS: (SHORT: 'm', LONG: 'mjeseci'),
      SUFFIX: (SHORT: 'ranije', LONG: 'ranije'),
      ONE_YEAR: (SHORT: 'g', LONG: 'jedna godina'),
      YEARS: (SHORT: 'g', LONG: 'godine'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'ca': TimeagoSymbol(
      JUST_NOW: (SHORT: 'ara', LONG: 'ara mateix'),
      SECONDS: (SHORT: 's', LONG: 'segons'),
      ONE_MINUTE: (SHORT: 'm', LONG: 'un minut'),
      MINUTES: (SHORT: 'm', LONG: 'minuts'),
      ONE_HOUR: (SHORT: 'h', LONG: 'una hora'),
      HOURS: (SHORT: 'h', LONG: 'hores'),
      ONE_DAY: (SHORT: 'd', LONG: 'un dia'),
      DAYS: (SHORT: 'd', LONG: 'dies'),
      ONE_MONTH: (SHORT: 'm', LONG: 'un mes'),
      MONTHS: (SHORT: 'm', LONG: 'mesos'),
      SUFFIX: (SHORT: 'fa', LONG: 'fa'),
      ONE_YEAR: (SHORT: 'a', LONG: 'un any'),
      YEARS: (SHORT: 'a', LONG: 'anys'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'chr': TimeagoSymbol(
      JUST_NOW: (SHORT: 'ᎠᏟᎠᎵ', LONG: 'ᎠᏟᎠᎵ'),
      SECONDS: (SHORT: 'Ꮝ', LONG: 'ᏍᎦᏂᏍᎩ'),
      ONE_MINUTE: (SHORT: 'Ꭴ', LONG: 'ᎯᎠ ᎤᏍᏗ'),
      MINUTES: (SHORT: 'Ꭴ', LONG: 'ᎤᏍᏗ'),
      ONE_HOUR: (SHORT: 'Ꮕ', LONG: 'ᎯᎠ ᏧᏂᏍᏗ'),
      HOURS: (SHORT: 'Ꮕ', LONG: 'ᏧᏂᏍᏗ'),
      ONE_DAY: (SHORT: 'Ꮤ', LONG: 'ᎯᎠ ᏑᏓᎵ'),
      DAYS: (SHORT: 'Ꮤ', LONG: 'ᏑᏓᎵ'),
      ONE_MONTH: (SHORT: 'Ꮕ', LONG: 'ᎯᎠ ᏧᏔᏂ'),
      MONTHS: (SHORT: 'Ꮕ', LONG: 'ᏧᏔᏂ'),
      SUFFIX: (SHORT: 'ᎠᏍᎦᏯ', LONG: 'ᎠᏍᎦᏯ'),
      ONE_YEAR: (SHORT: 'Ꮝ', LONG: 'ᎯᎠ ᏅᏙᎢ'),
      YEARS: (SHORT: 'Ꮝ', LONG: 'ᏅᏙᎢ'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'cs': TimeagoSymbol(
      JUST_NOW: (SHORT: 'nyní', LONG: 'právě teď'),
      SECONDS: (SHORT: 's', LONG: 'sekund'),
      ONE_MINUTE: (SHORT: 'm', LONG: 'minuta'),
      MINUTES: (SHORT: 'm', LONG: 'minut'),
      ONE_HOUR: (SHORT: 'h', LONG: 'hodina'),
      HOURS: (SHORT: 'h', LONG: 'hodin'),
      ONE_DAY: (SHORT: 'd', LONG: 'den'),
      DAYS: (SHORT: 'd', LONG: 'dny'),
      ONE_MONTH: (SHORT: 'm', LONG: 'měsíc'),
      MONTHS: (SHORT: 'm', LONG: 'měsíců'),
      SUFFIX: (SHORT: 'před', LONG: 'před'),
      ONE_YEAR: (SHORT: 'r', LONG: 'rok'),
      YEARS: (SHORT: 'r', LONG: 'let'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'cy': TimeagoSymbol(
      JUST_NOW: (SHORT: 'rwan', LONG: 'rwan'),
      SECONDS: (SHORT: 's', LONG: 'eiliad'),
      ONE_MINUTE: (SHORT: 'm', LONG: 'munud'),
      MINUTES: (SHORT: 'm', LONG: 'munud'),
      ONE_HOUR: (SHORT: 'h', LONG: 'awr'),
      HOURS: (SHORT: 'h', LONG: 'awr'),
      ONE_DAY: (SHORT: 'd', LONG: 'diwrnod'),
      DAYS: (SHORT: 'd', LONG: 'diwrnod'),
      ONE_MONTH: (SHORT: 'm', LONG: 'mis'),
      MONTHS: (SHORT: 'm', LONG: 'mis'),
      SUFFIX: (SHORT: 'yn ôl', LONG: 'yn ôl'),
      ONE_YEAR: (SHORT: 'b', LONG: 'blwyddyn'),
      YEARS: (SHORT: 'b', LONG: 'blwyddyn'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'da': TimeagoSymbol(
      JUST_NOW: (SHORT: 'nu', LONG: 'lige nu'),
      SECONDS: (SHORT: 's', LONG: 'sekunder'),
      ONE_MINUTE: (SHORT: 'm', LONG: 'et minut'),
      MINUTES: (SHORT: 'm', LONG: 'minutter'),
      ONE_HOUR: (SHORT: 't', LONG: 'en time'),
      HOURS: (SHORT: 't', LONG: 'timer'),
      ONE_DAY: (SHORT: 'd', LONG: 'en dag'),
      DAYS: (SHORT: 'd', LONG: 'dage'),
      ONE_MONTH: (SHORT: 'm', LONG: 'en måned'),
      MONTHS: (SHORT: 'm', LONG: 'måneder'),
      SUFFIX: (SHORT: 'siden', LONG: 'siden'),
      ONE_YEAR: (SHORT: 'å', LONG: 'et år'),
      YEARS: (SHORT: 'å', LONG: 'år'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'de': TimeagoSymbol(
      JUST_NOW: (SHORT: 'jetzt', LONG: 'gerade jetzt'),
      SECONDS: (SHORT: 's', LONG: 'Sekunden'),
      ONE_MINUTE: (SHORT: 'm', LONG: 'eine Minute'),
      MINUTES: (SHORT: 'm', LONG: 'Minuten'),
      ONE_HOUR: (SHORT: 'h', LONG: 'eine Stunde'),
      HOURS: (SHORT: 'h', LONG: 'Stunden'),
      ONE_DAY: (SHORT: 't', LONG: 'ein Tag'),
      DAYS: (SHORT: 't', LONG: 'Tage'),
      ONE_MONTH: (SHORT: 'm', LONG: 'ein Monat'),
      MONTHS: (SHORT: 'm', LONG: 'Monate'),
      SUFFIX: (SHORT: 'vor', LONG: 'vor'),
      ONE_YEAR: (SHORT: 'j', LONG: 'ein Jahr'),
      YEARS: (SHORT: 'j', LONG: 'Jahre'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'de_AT': TimeagoSymbol(
      JUST_NOW: (SHORT: 'jetzt', LONG: 'gerade jetzt'),
      SECONDS: (SHORT: 's', LONG: 'Sekunden'),
      ONE_MINUTE: (SHORT: 'm', LONG: 'eine Minute'),
      MINUTES: (SHORT: 'm', LONG: 'Minuten'),
      ONE_HOUR: (SHORT: 'h', LONG: 'eine Stunde'),
      HOURS: (SHORT: 'h', LONG: 'Stunden'),
      ONE_DAY: (SHORT: 't', LONG: 'ein Tag'),
      DAYS: (SHORT: 't', LONG: 'Tage'),
      ONE_MONTH: (SHORT: 'm', LONG: 'ein Monat'),
      MONTHS: (SHORT: 'm', LONG: 'Monate'),
      SUFFIX: (SHORT: 'vor', LONG: 'vor'),
      ONE_YEAR: (SHORT: 'j', LONG: 'ein Jahr'),
      YEARS: (SHORT: 'j', LONG: 'Jahre'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'de_CH': TimeagoSymbol(
      JUST_NOW: (SHORT: 'jetzt', LONG: 'gerade jetzt'),
      SECONDS: (SHORT: 's', LONG: 'Sekunden'),
      ONE_MINUTE: (SHORT: 'm', LONG: 'eine Minute'),
      MINUTES: (SHORT: 'm', LONG: 'Minuten'),
      ONE_HOUR: (SHORT: 'h', LONG: 'eine Stunde'),
      HOURS: (SHORT: 'h', LONG: 'Stunden'),
      ONE_DAY: (SHORT: 't', LONG: 'ein Tag'),
      DAYS: (SHORT: 't', LONG: 'Tage'),
      ONE_MONTH: (SHORT: 'm', LONG: 'ein Monat'),
      MONTHS: (SHORT: 'm', LONG: 'Monate'),
      SUFFIX: (SHORT: 'vor', LONG: 'vor'),
      ONE_YEAR: (SHORT: 'j', LONG: 'ein Jahr'),
      YEARS: (SHORT: 'j', LONG: 'Jahre'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'el': TimeagoSymbol(
      JUST_NOW: (SHORT: 'τώρα', LONG: 'μόλις τώρα'),
      SECONDS: (SHORT: 'δ', LONG: 'δευτερόλεπτα'),
      ONE_MINUTE: (SHORT: 'λ', LONG: 'ένα λεπτό'),
      MINUTES: (SHORT: 'λ', LONG: 'λεπτά'),
      ONE_HOUR: (SHORT: 'ώ', LONG: 'μία ώρα'),
      HOURS: (SHORT: 'ώ', LONG: 'ώρες'),
      ONE_DAY: (SHORT: 'μ', LONG: 'μία μέρα'),
      DAYS: (SHORT: 'μ', LONG: 'μέρες'),
      ONE_MONTH: (SHORT: 'μ', LONG: 'ένας μήνας'),
      MONTHS: (SHORT: 'μ', LONG: 'μήνες'),
      SUFFIX: (SHORT: 'πριν', LONG: 'πριν'),
      ONE_YEAR: (SHORT: 'χ', LONG: 'ένα χρόνο'),
      YEARS: (SHORT: 'χ', LONG: 'χρόνια'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'es': TimeagoSymbol(
      JUST_NOW: (SHORT: 'ahora', LONG: 'justo ahora'),
      SECONDS: (SHORT: 's', LONG: 'segundos'),
      ONE_MINUTE: (SHORT: 'm', LONG: 'un minuto'),
      MINUTES: (SHORT: 'm', LONG: 'minutos'),
      ONE_HOUR: (SHORT: 'h', LONG: 'una hora'),
      HOURS: (SHORT: 'h', LONG: 'horas'),
      ONE_DAY: (SHORT: 'd', LONG: 'un día'),
      DAYS: (SHORT: 'd', LONG: 'días'),
      ONE_MONTH: (SHORT: 'm', LONG: 'un mes'),
      MONTHS: (SHORT: 'm', LONG: 'meses'),
      SUFFIX: (SHORT: 'hace', LONG: 'hace'),
      ONE_YEAR: (SHORT: 'a', LONG: 'un año'),
      YEARS: (SHORT: 'a', LONG: 'años'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'es_419': TimeagoSymbol(
      JUST_NOW: (SHORT: 'ahora', LONG: 'justo ahora'),
      SECONDS: (SHORT: 's', LONG: 'segundos'),
      ONE_MINUTE: (SHORT: 'm', LONG: 'un minuto'),
      MINUTES: (SHORT: 'm', LONG: 'minutos'),
      ONE_HOUR: (SHORT: 'h', LONG: 'una hora'),
      HOURS: (SHORT: 'h', LONG: 'horas'),
      ONE_DAY: (SHORT: 'd', LONG: 'un día'),
      DAYS: (SHORT: 'd', LONG: 'días'),
      ONE_MONTH: (SHORT: 'm', LONG: 'un mes'),
      MONTHS: (SHORT: 'm', LONG: 'meses'),
      SUFFIX: (SHORT: 'hace', LONG: 'hace'),
      ONE_YEAR: (SHORT: 'a', LONG: 'un año'),
      YEARS: (SHORT: 'a', LONG: 'años'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'es_ES': TimeagoSymbol(
      JUST_NOW: (SHORT: 'ahora', LONG: 'justo ahora'),
      SECONDS: (SHORT: 's', LONG: 'segundos'),
      ONE_MINUTE: (SHORT: 'm', LONG: 'un minuto'),
      MINUTES: (SHORT: 'm', LONG: 'minutos'),
      ONE_HOUR: (SHORT: 'h', LONG: 'una hora'),
      HOURS: (SHORT: 'h', LONG: 'horas'),
      ONE_DAY: (SHORT: 'd', LONG: 'un día'),
      DAYS: (SHORT: 'd', LONG: 'días'),
      ONE_MONTH: (SHORT: 'm', LONG: 'un mes'),
      MONTHS: (SHORT: 'm', LONG: 'meses'),
      SUFFIX: (SHORT: 'hace', LONG: 'hace'),
      ONE_YEAR: (SHORT: 'a', LONG: 'un año'),
      YEARS: (SHORT: 'a', LONG: 'años'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'es_MX': TimeagoSymbol(
      JUST_NOW: (SHORT: 'ahora', LONG: 'justo ahora'),
      SECONDS: (SHORT: 's', LONG: 'segundos'),
      ONE_MINUTE: (SHORT: 'm', LONG: 'un minuto'),
      MINUTES: (SHORT: 'm', LONG: 'minutos'),
      ONE_HOUR: (SHORT: 'h', LONG: 'una hora'),
      HOURS: (SHORT: 'h', LONG: 'horas'),
      ONE_DAY: (SHORT: 'd', LONG: 'un día'),
      DAYS: (SHORT: 'd', LONG: 'días'),
      ONE_MONTH: (SHORT: 'm', LONG: 'un mes'),
      MONTHS: (SHORT: 'm', LONG: 'meses'),
      SUFFIX: (SHORT: 'hace', LONG: 'hace'),
      ONE_YEAR: (SHORT: 'a', LONG: 'un año'),
      YEARS: (SHORT: 'a', LONG: 'años'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'es_US': TimeagoSymbol(
      JUST_NOW: (SHORT: 'ahora', LONG: 'justo ahora'),
      SECONDS: (SHORT: 's', LONG: 'segundos'),
      ONE_MINUTE: (SHORT: 'm', LONG: 'un minuto'),
      MINUTES: (SHORT: 'm', LONG: 'minutos'),
      ONE_HOUR: (SHORT: 'h', LONG: 'una hora'),
      HOURS: (SHORT: 'h', LONG: 'horas'),
      ONE_DAY: (SHORT: 'd', LONG: 'un día'),
      DAYS: (SHORT: 'd', LONG: 'días'),
      ONE_MONTH: (SHORT: 'm', LONG: 'un mes'),
      MONTHS: (SHORT: 'm', LONG: 'meses'),
      SUFFIX: (SHORT: 'hace', LONG: 'hace'),
      ONE_YEAR: (SHORT: 'a', LONG: 'un año'),
      YEARS: (SHORT: 'a', LONG: 'años'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'et': TimeagoSymbol(
      JUST_NOW: (SHORT: 'nüüd', LONG: 'just nüüd'),
      SECONDS: (SHORT: 's', LONG: 'sekundit'),
      ONE_MINUTE: (SHORT: 'm', LONG: 'üks minut'),
      MINUTES: (SHORT: 'm', LONG: 'minutit'),
      ONE_HOUR: (SHORT: 't', LONG: 'üks tund'),
      HOURS: (SHORT: 't', LONG: 'tundi'),
      ONE_DAY: (SHORT: 'p', LONG: 'üks päev'),
      DAYS: (SHORT: 'p', LONG: 'päeva'),
      ONE_MONTH: (SHORT: 'k', LONG: 'üks kuu'),
      MONTHS: (SHORT: 'k', LONG: 'kuud'),
      SUFFIX: (SHORT: 'tagasi', LONG: 'tagasi'),
      ONE_YEAR: (SHORT: 'a', LONG: 'üks aasta'),
      YEARS: (SHORT: 'a', LONG: 'aastat'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'eu': TimeagoSymbol(
      JUST_NOW: (SHORT: 'orain', LONG: 'orain'),
      SECONDS: (SHORT: 's', LONG: 'segundu'),
      ONE_MINUTE: (SHORT: 'm', LONG: 'minutu bat'),
      MINUTES: (SHORT: 'm', LONG: 'minutu'),
      ONE_HOUR: (SHORT: 'o', LONG: 'ordu bat'),
      HOURS: (SHORT: 'o', LONG: 'ordu'),
      ONE_DAY: (SHORT: 'e', LONG: 'egun bat'),
      DAYS: (SHORT: 'e', LONG: 'egun'),
      ONE_MONTH: (SHORT: 'h', LONG: 'hilabete bat'),
      MONTHS: (SHORT: 'h', LONG: 'hilabete'),
      SUFFIX: (SHORT: 'duela', LONG: 'duela'),
      ONE_YEAR: (SHORT: 'u', LONG: 'urte bat'),
      YEARS: (SHORT: 'u', LONG: 'urte'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'fa': TimeagoSymbol(
      JUST_NOW: (SHORT: 'اکنون', LONG: 'اکنون'),
      SECONDS: (SHORT: 'ث', LONG: 'ثانیه'),
      ONE_MINUTE: (SHORT: 'د', LONG: 'یک دقیقه'),
      MINUTES: (SHORT: 'د', LONG: 'دقیقه'),
      ONE_HOUR: (SHORT: 'س', LONG: 'یک ساعت'),
      HOURS: (SHORT: 'س', LONG: 'ساعت'),
      ONE_DAY: (SHORT: 'ر', LONG: 'یک روز'),
      DAYS: (SHORT: 'ر', LONG: 'روز'),
      ONE_MONTH: (SHORT: 'م', LONG: 'یک ماه'),
      MONTHS: (SHORT: 'م', LONG: 'ماه'),
      SUFFIX: (SHORT: 'پیش', LONG: 'پیش'),
      ONE_YEAR: (SHORT: 'س', LONG: 'یک سال'),
      YEARS: (SHORT: 'س', LONG: 'سال'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'fi': TimeagoSymbol(
      JUST_NOW: (SHORT: 'nyt', LONG: 'juuri nyt'),
      SECONDS: (SHORT: 's', LONG: 'sekuntia'),
      ONE_MINUTE: (SHORT: 'm', LONG: 'minuutti'),
      MINUTES: (SHORT: 'm', LONG: 'minuuttia'),
      ONE_HOUR: (SHORT: 't', LONG: 'tunti'),
      HOURS: (SHORT: 't', LONG: 'tuntia'),
      ONE_DAY: (SHORT: 'p', LONG: 'päivä'),
      DAYS: (SHORT: 'p', LONG: 'päivää'),
      ONE_MONTH: (SHORT: 'k', LONG: 'kuukausi'),
      MONTHS: (SHORT: 'k', LONG: 'kuukautta'),
      SUFFIX: (SHORT: 'sitten', LONG: 'sitten'),
      ONE_YEAR: (SHORT: 'v', LONG: 'vuosi'),
      YEARS: (SHORT: 'v', LONG: 'vuotta'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'fil': TimeagoSymbol(
      JUST_NOW: (SHORT: 'ngayon', LONG: 'ngayon lang'),
      SECONDS: (SHORT: 's', LONG: 'segundo'),
      ONE_MINUTE: (SHORT: 'm', LONG: 'isang minuto'),
      MINUTES: (SHORT: 'm', LONG: 'minuto'),
      ONE_HOUR: (SHORT: 'h', LONG: 'isang oras'),
      HOURS: (SHORT: 'h', LONG: 'oras'),
      ONE_DAY: (SHORT: 'a', LONG: 'isang araw'),
      DAYS: (SHORT: 'a', LONG: 'araw'),
      ONE_MONTH: (SHORT: 'b', LONG: 'isang buwan'),
      MONTHS: (SHORT: 'b', LONG: 'buwan'),
      SUFFIX: (SHORT: 'na', LONG: 'na'),
      ONE_YEAR: (SHORT: 't', LONG: 'isang taon'),
      YEARS: (SHORT: 't', LONG: 'taon'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'fr': TimeagoSymbol(
      JUST_NOW: (SHORT: 'maintenant', LONG: 'à l\'instant'),
      SECONDS: (SHORT: 's', LONG: 'secondes'),
      ONE_MINUTE: (SHORT: 'm', LONG: 'une minute'),
      MINUTES: (SHORT: 'm', LONG: 'minutes'),
      ONE_HOUR: (SHORT: 'h', LONG: 'une heure'),
      HOURS: (SHORT: 'h', LONG: 'heures'),
      ONE_DAY: (SHORT: 'j', LONG: 'un jour'),
      DAYS: (SHORT: 'j', LONG: 'jours'),
      ONE_MONTH: (SHORT: 'm', LONG: 'un mois'),
      MONTHS: (SHORT: 'm', LONG: 'mois'),
      SUFFIX: (SHORT: 'il y a', LONG: 'il y a'),
      ONE_YEAR: (SHORT: 'a', LONG: 'un an'),
      YEARS: (SHORT: 'a', LONG: 'ans'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'fr_CA': TimeagoSymbol(
      JUST_NOW: (SHORT: 'maintenant', LONG: 'à l\'instant'),
      SECONDS: (SHORT: 's', LONG: 'secondes'),
      ONE_MINUTE: (SHORT: 'm', LONG: 'minute'),
      MINUTES: (SHORT: 'm', LONG: 'minutes'),
      ONE_HOUR: (SHORT: 'h', LONG: 'heure'),
      HOURS: (SHORT: 'h', LONG: 'heures'),
      ONE_DAY: (SHORT: 'j', LONG: 'jour'),
      DAYS: (SHORT: 'j', LONG: 'jours'),
      ONE_MONTH: (SHORT: 'mois', LONG: 'mois'),
      MONTHS: (SHORT: 'mois', LONG: 'mois'),
      SUFFIX: (SHORT: 'il y a', LONG: 'il y a'),
      ONE_YEAR: (SHORT: 'an', LONG: 'an'),
      YEARS: (SHORT: 'ans', LONG: 'ans'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'fr_CH': TimeagoSymbol(
      JUST_NOW: (SHORT: 'maintenant', LONG: 'à l\'instant'),
      SECONDS: (SHORT: 's', LONG: 'secondes'),
      ONE_MINUTE: (SHORT: 'min', LONG: 'minute'),
      MINUTES: (SHORT: 'min', LONG: 'minutes'),
      ONE_HOUR: (SHORT: 'h', LONG: 'heure'),
      HOURS: (SHORT: 'h', LONG: 'heures'),
      ONE_DAY: (SHORT: 'j', LONG: 'jour'),
      DAYS: (SHORT: 'j', LONG: 'jours'),
      ONE_MONTH: (SHORT: 'mois', LONG: 'mois'),
      MONTHS: (SHORT: 'mois', LONG: 'mois'),
      SUFFIX: (SHORT: 'il y a', LONG: 'il y a'),
      ONE_YEAR: (SHORT: 'an', LONG: 'an'),
      YEARS: (SHORT: 'ans', LONG: 'ans'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'fur': TimeagoSymbol(
      JUST_NOW: (SHORT: 'subito', LONG: 'proprio adesso'),
      SECONDS: (SHORT: 's', LONG: 'secondi'),
      ONE_MINUTE: (SHORT: 'm', LONG: 'minuto'),
      MINUTES: (SHORT: 'm', LONG: 'minuti'),
      ONE_HOUR: (SHORT: 'h', LONG: 'ora'),
      HOURS: (SHORT: 'h', LONG: 'ore'),
      ONE_DAY: (SHORT: 'g', LONG: 'giorno'),
      DAYS: (SHORT: 'g', LONG: 'giorni'),
      ONE_MONTH: (SHORT: 'm', LONG: 'mese'),
      MONTHS: (SHORT: 'm', LONG: 'mesi'),
      SUFFIX: (SHORT: 'fa', LONG: 'fa'),
      ONE_YEAR: (SHORT: 'a', LONG: 'anno'),
      YEARS: (SHORT: 'a', LONG: 'anni'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'ga': TimeagoSymbol(
      JUST_NOW: (SHORT: 'anois', LONG: 'anoisín'),
      SECONDS: (SHORT: 's', LONG: 'soicind'),
      ONE_MINUTE: (SHORT: 'nóim', LONG: 'nóiméad'),
      MINUTES: (SHORT: 'nóim', LONG: 'nóiméid'),
      ONE_HOUR: (SHORT: 'u', LONG: 'uair'),
      HOURS: (SHORT: 'u', LONG: 'uair'),
      ONE_DAY: (SHORT: 'l', LONG: 'lá'),
      DAYS: (SHORT: 'l', LONG: 'laethanta'),
      ONE_MONTH: (SHORT: 'm', LONG: 'mí'),
      MONTHS: (SHORT: 'm', LONG: 'míonna'),
      SUFFIX: (SHORT: 'ó shin', LONG: 'ó shin'),
      ONE_YEAR: (SHORT: 'b', LONG: 'bhliain'),
      YEARS: (SHORT: 'b', LONG: 'bhliain'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'gl': TimeagoSymbol(
      JUST_NOW: (SHORT: 'xusto agora', LONG: 'agora mesmo'),
      SECONDS: (SHORT: 's', LONG: 'segundos'),
      ONE_MINUTE: (SHORT: 'm', LONG: 'minuto'),
      MINUTES: (SHORT: 'm', LONG: 'minutos'),
      ONE_HOUR: (SHORT: 'h', LONG: 'hora'),
      HOURS: (SHORT: 'h', LONG: 'horas'),
      ONE_DAY: (SHORT: 'd', LONG: 'día'),
      DAYS: (SHORT: 'd', LONG: 'días'),
      ONE_MONTH: (SHORT: 'm', LONG: 'mes'),
      MONTHS: (SHORT: 'm', LONG: 'meses'),
      SUFFIX: (SHORT: 'atrás', LONG: 'atrás'),
      ONE_YEAR: (SHORT: 'a', LONG: 'ano'),
      YEARS: (SHORT: 'a', LONG: 'anos'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'gu': TimeagoSymbol(
      JUST_NOW: (SHORT: 'હવે', LONG: 'આ સમયે'),
      SECONDS: (SHORT: 'સેક', LONG: 'સેકંડ'),
      ONE_MINUTE: (SHORT: 'મિ', LONG: 'મિનિટ'),
      MINUTES: (SHORT: 'મિ', LONG: 'મિનિટ'),
      ONE_HOUR: (SHORT: 'ક', LONG: 'કલાક'),
      HOURS: (SHORT: 'ક', LONG: 'કલાક'),
      ONE_DAY: (SHORT: 'દિ', LONG: 'દિવસ'),
      DAYS: (SHORT: 'દિ', LONG: 'દિવસ'),
      ONE_MONTH: (SHORT: 'મહિનો', LONG: 'મહિનો'),
      MONTHS: (SHORT: 'મહિના', LONG: 'મહિના'),
      SUFFIX: (SHORT: 'પહેલા', LONG: 'પહેલા'),
      ONE_YEAR: (SHORT: 'વર્ષ', LONG: 'વર્ષ'),
      YEARS: (SHORT: 'વર્ષો', LONG: 'વર્ષો'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'gsw': TimeagoSymbol(
      JUST_NOW: (SHORT: 'jetzt', LONG: 'gerade jetzt'),
      SECONDS: (SHORT: 's', LONG: 'Sekunden'),
      ONE_MINUTE: (SHORT: 'm', LONG: 'eine Minute'),
      MINUTES: (SHORT: 'm', LONG: 'Minuten'),
      ONE_HOUR: (SHORT: 'h', LONG: 'eine Stunde'),
      HOURS: (SHORT: 'h', LONG: 'Stunden'),
      ONE_DAY: (SHORT: 't', LONG: 'ein Tag'),
      DAYS: (SHORT: 't', LONG: 'Tage'),
      ONE_MONTH: (SHORT: 'm', LONG: 'ein Monat'),
      MONTHS: (SHORT: 'm', LONG: 'Monate'),
      SUFFIX: (SHORT: 'vor', LONG: 'vor'),
      ONE_YEAR: (SHORT: 'j', LONG: 'ein Jahr'),
      YEARS: (SHORT: 'j', LONG: 'Jahre'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'haw': TimeagoSymbol(
      JUST_NOW: (SHORT: 'kēia manawa', LONG: 'ma ka wā kēia'),
      SECONDS: (SHORT: 'sek', LONG: 'sekona'),
      ONE_MINUTE: (SHORT: 'min', LONG: 'minuke'),
      MINUTES: (SHORT: 'min', LONG: 'minuke'),
      ONE_HOUR: (SHORT: 'h', LONG: 'hola'),
      HOURS: (SHORT: 'h', LONG: 'hola'),
      ONE_DAY: (SHORT: 'lā', LONG: 'lā'),
      DAYS: (SHORT: 'lā', LONG: 'lā'),
      ONE_MONTH: (SHORT: 'mah', LONG: 'mahina'),
      MONTHS: (SHORT: 'mah', LONG: 'mahina'),
      SUFFIX: (SHORT: 'i kēia manawa', LONG: 'i kēia manawa'),
      ONE_YEAR: (SHORT: 'mak', LONG: 'makahiki'),
      YEARS: (SHORT: 'mak', LONG: 'makahiki'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'he': TimeagoSymbol(
      JUST_NOW: (SHORT: 'עכשיו', LONG: 'כרגע'),
      SECONDS: (SHORT: 'שניות', LONG: 'שניה'),
      ONE_MINUTE: (SHORT: 'דקה', LONG: 'דקה'),
      MINUTES: (SHORT: 'דקות', LONG: 'דקות'),
      ONE_HOUR: (SHORT: 'שעה', LONG: 'שעה'),
      HOURS: (SHORT: 'שעות', LONG: 'שעות'),
      ONE_DAY: (SHORT: 'יום', LONG: 'יום'),
      DAYS: (SHORT: 'ימים', LONG: 'ימים'),
      ONE_MONTH: (SHORT: 'חודש', LONG: 'חודש'),
      MONTHS: (SHORT: 'חודשים', LONG: 'חודשים'),
      SUFFIX: (SHORT: 'לפני', LONG: 'לפני'),
      ONE_YEAR: (SHORT: 'שנה', LONG: 'שנה'),
      YEARS: (SHORT: 'שנים', LONG: 'שנים'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'hi': TimeagoSymbol(
      JUST_NOW: (SHORT: 'अभी', LONG: 'अभी'),
      SECONDS: (SHORT: 'सेकंड', LONG: 'सेकंड'),
      ONE_MINUTE: (SHORT: 'मिनट', LONG: 'मिनट'),
      MINUTES: (SHORT: 'मिनट', LONG: 'मिनट'),
      ONE_HOUR: (SHORT: 'घंटा', LONG: 'घंटा'),
      HOURS: (SHORT: 'घंटे', LONG: 'घंटे'),
      ONE_DAY: (SHORT: 'दिन', LONG: 'दिन'),
      DAYS: (SHORT: 'दिन', LONG: 'दिन'),
      ONE_MONTH: (SHORT: 'महीना', LONG: 'महीना'),
      MONTHS: (SHORT: 'मही', LONG: 'महीने'),
      SUFFIX: (SHORT: 'पूर्व', LONG: 'पहले'),
      ONE_YEAR: (SHORT: 'वर्ष', LONG: 'वर्ष'),
      YEARS: (SHORT: 'वर्ष', LONG: 'वर्ष'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'hr': TimeagoSymbol(
      JUST_NOW: (SHORT: 'upravo', LONG: 'upravo sada'),
      SECONDS: (SHORT: 's', LONG: 'sekunde'),
      ONE_MINUTE: (SHORT: 'min', LONG: 'minuta'),
      MINUTES: (SHORT: 'min', LONG: 'minuta'),
      ONE_HOUR: (SHORT: 'h', LONG: 'sat'),
      HOURS: (SHORT: 'h', LONG: 'sata'),
      ONE_DAY: (SHORT: 'dan', LONG: 'dan'),
      DAYS: (SHORT: 'd', LONG: 'dana'),
      ONE_MONTH: (SHORT: 'mj', LONG: 'mjesec'),
      MONTHS: (SHORT: 'mj', LONG: 'mjeseci'),
      SUFFIX: (SHORT: 'prije', LONG: 'prije'),
      ONE_YEAR: (SHORT: 'god', LONG: 'godina'),
      YEARS: (SHORT: 'g', LONG: 'godina'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'hu': TimeagoSymbol(
      JUST_NOW: (SHORT: 'éppen most', LONG: 'épp most'),
      SECONDS: (SHORT: 's', LONG: 'másodperc'),
      ONE_MINUTE: (SHORT: 'p', LONG: 'perc'),
      MINUTES: (SHORT: 'p', LONG: 'perc'),
      ONE_HOUR: (SHORT: 'ó', LONG: 'óra'),
      HOURS: (SHORT: 'ó', LONG: 'óra'),
      ONE_DAY: (SHORT: 'n', LONG: 'nap'),
      DAYS: (SHORT: 'n', LONG: 'nap'),
      ONE_MONTH: (SHORT: 'h', LONG: 'hónap'),
      MONTHS: (SHORT: 'h', LONG: 'hónap'),
      SUFFIX: (SHORT: 'el', LONG: 'el'),
      ONE_YEAR: (SHORT: 'év', LONG: 'év'),
      YEARS: (SHORT: 'év', LONG: 'év'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'hy': TimeagoSymbol(
      JUST_NOW: (SHORT: 'հիմա', LONG: 'հետո'),
      SECONDS: (SHORT: 'վ', LONG: 'վարկյան'),
      ONE_MINUTE: (SHORT: 'ր', LONG: 'րոպիկ'),
      MINUTES: (SHORT: 'ր', LONG: 'րոպե'),
      ONE_HOUR: (SHORT: 'ժ', LONG: 'ժամ'),
      HOURS: (SHORT: 'ժ', LONG: 'ժամ'),
      ONE_DAY: (SHORT: 'օր', LONG: 'օր'),
      DAYS: (SHORT: 'օր', LONG: 'օր'),
      ONE_MONTH: (SHORT: 'ամ', LONG: 'ամիս'),
      MONTHS: (SHORT: 'ամ', LONG: 'ամիս'),
      SUFFIX: (SHORT: 'առաջ', LONG: 'առաջ'),
      ONE_YEAR: (SHORT: 'տա', LONG: 'տարի'),
      YEARS: (SHORT: 'տա', LONG: 'տարի'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'id': TimeagoSymbol(
      JUST_NOW: (SHORT: 'baru saja', LONG: 'baru saja'),
      SECONDS: (SHORT: 'd', LONG: 'detik'),
      ONE_MINUTE: (SHORT: 'm', LONG: 'menit'),
      MINUTES: (SHORT: 'm', LONG: 'menit'),
      ONE_HOUR: (SHORT: 'j', LONG: 'jam'),
      HOURS: (SHORT: 'j', LONG: 'jam'),
      ONE_DAY: (SHORT: 'h', LONG: 'hari'),
      DAYS: (SHORT: 'h', LONG: 'hari'),
      ONE_MONTH: (SHORT: 'b', LONG: 'bulan'),
      MONTHS: (SHORT: 'b', LONG: 'bulan'),
      SUFFIX: (SHORT: 'yang lalu', LONG: 'yang lalu'),
      ONE_YEAR: (SHORT: 't', LONG: 'tahun'),
      YEARS: (SHORT: 't', LONG: 'tahun'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'in': TimeagoSymbol(
      JUST_NOW: (SHORT: 'अभी', LONG: 'अभी'),
      SECONDS: (SHORT: 'से', LONG: 'सेकंड'),
      ONE_MINUTE: (SHORT: 'मि', LONG: 'मिनट'),
      MINUTES: (SHORT: 'मि', LONG: 'मिनट'),
      ONE_HOUR: (SHORT: 'घं', LONG: 'घंटा'),
      HOURS: (SHORT: 'घं', LONG: 'घंटे'),
      ONE_DAY: (SHORT: 'दिन', LONG: 'दिन'),
      DAYS: (SHORT: 'दिन', LONG: 'दिन'),
      ONE_MONTH: (SHORT: 'मही', LONG: 'महीना'),
      MONTHS: (SHORT: 'मही', LONG: 'महीने'),
      SUFFIX: (SHORT: 'पहले', LONG: 'पहले'),
      ONE_YEAR: (SHORT: 'वर्ष', LONG: 'वर्ष'),
      YEARS: (SHORT: 'वर्ष', LONG: 'वर्ष'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'is': TimeagoSymbol(
      JUST_NOW: (SHORT: 'núna', LONG: 'núna'),
      SECONDS: (SHORT: 's', LONG: 'sekúnda'),
      ONE_MINUTE: (SHORT: 'm', LONG: 'mínúta'),
      MINUTES: (SHORT: 'm', LONG: 'mínútur'),
      ONE_HOUR: (SHORT: 'kl', LONG: 'klukkustund'),
      HOURS: (SHORT: 'kl', LONG: 'klukkustundir'),
      ONE_DAY: (SHORT: 'd', LONG: 'dagur'),
      DAYS: (SHORT: 'd', LONG: 'dagar'),
      ONE_MONTH: (SHORT: 'mán', LONG: 'mánuður'),
      MONTHS: (SHORT: 'mán', LONG: 'mánuðir'),
      SUFFIX: (SHORT: 'síðan', LONG: 'síðan'),
      ONE_YEAR: (SHORT: 'á', LONG: 'ár'),
      YEARS: (SHORT: 'á', LONG: 'ár'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'it': TimeagoSymbol(
      JUST_NOW: (SHORT: 'ora', LONG: 'proprio ora'),
      SECONDS: (SHORT: 's', LONG: 'secondo'),
      ONE_MINUTE: (SHORT: 'm', LONG: 'minuto'),
      MINUTES: (SHORT: 'm', LONG: 'minuti'),
      ONE_HOUR: (SHORT: 'o', LONG: 'ora'),
      HOURS: (SHORT: 'o', LONG: 'ore'),
      ONE_DAY: (SHORT: 'g', LONG: 'giorno'),
      DAYS: (SHORT: 'g', LONG: 'giorni'),
      ONE_MONTH: (SHORT: 'm', LONG: 'mese'),
      MONTHS: (SHORT: 'm', LONG: 'mesi'),
      SUFFIX: (SHORT: 'fa', LONG: 'fa'),
      ONE_YEAR: (SHORT: 'a', LONG: 'anno'),
      YEARS: (SHORT: 'a', LONG: 'anni'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'it_CH': TimeagoSymbol(
      JUST_NOW: (SHORT: 'ora', LONG: 'proprio ora'),
      SECONDS: (SHORT: 's', LONG: 'secondo'),
      ONE_MINUTE: (SHORT: 'm', LONG: 'minuto'),
      MINUTES: (SHORT: 'm', LONG: 'minuti'),
      ONE_HOUR: (SHORT: 'o', LONG: 'ora'),
      HOURS: (SHORT: 'o', LONG: 'ore'),
      ONE_DAY: (SHORT: 'g', LONG: 'giorno'),
      DAYS: (SHORT: 'g', LONG: 'giorni'),
      ONE_MONTH: (SHORT: 'm', LONG: 'mese'),
      MONTHS: (SHORT: 'm', LONG: 'mesi'),
      SUFFIX: (SHORT: 'fa', LONG: 'fa'),
      ONE_YEAR: (SHORT: 'a', LONG: 'anno'),
      YEARS: (SHORT: 'a', LONG: 'anni'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'iw': TimeagoSymbol(
      JUST_NOW: (SHORT: 'עכשיו', LONG: 'כרגע'),
      SECONDS: (SHORT: 'שניות', LONG: 'שנייה'),
      ONE_MINUTE: (SHORT: 'דקה', LONG: 'דקה'),
      MINUTES: (SHORT: 'דקות', LONG: 'דקות'),
      ONE_HOUR: (SHORT: 'שעה', LONG: 'שעה'),
      HOURS: (SHORT: 'שעות', LONG: 'שעות'),
      ONE_DAY: (SHORT: 'יום', LONG: 'יום'),
      DAYS: (SHORT: 'ימים', LONG: 'ימים'),
      ONE_MONTH: (SHORT: 'חודש', LONG: 'חודש'),
      MONTHS: (SHORT: 'חודשים', LONG: 'חודשים'),
      SUFFIX: (SHORT: 'לפני', LONG: 'לפני'),
      ONE_YEAR: (SHORT: 'שנה', LONG: 'שנה'),
      YEARS: (SHORT: 'שנים', LONG: 'שנים'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'ja': TimeagoSymbol(
      JUST_NOW: (SHORT: 'たった今', LONG: 'ちょうど今'),
      SECONDS: (SHORT: '秒前', LONG: '秒前'),
      ONE_MINUTE: (SHORT: '1分前', LONG: '1分前'),
      MINUTES: (SHORT: '分前', LONG: '分前'),
      ONE_HOUR: (SHORT: '1時間前', LONG: '1時間前'),
      HOURS: (SHORT: '時間前', LONG: '時間前'),
      ONE_DAY: (SHORT: '1日前', LONG: '1日前'),
      DAYS: (SHORT: '日前', LONG: '日前'),
      ONE_MONTH: (SHORT: '1ヶ月前', LONG: '1ヶ月前'),
      MONTHS: (SHORT: 'ヶ月前', LONG: 'ヶ月前'),
      SUFFIX: (SHORT: '前', LONG: '前'),
      ONE_YEAR: (SHORT: '1年前', LONG: '1年前'),
      YEARS: (SHORT: '年前', LONG: '年前'),
      SEPARATOR: (SHORT: '', LONG: ''),
    ),
    'ka': TimeagoSymbol(
      JUST_NOW: (SHORT: 'ამდენიან', LONG: 'ამ წუთზე'),
      SECONDS: (SHORT: 'წ', LONG: 'წამი'),
      ONE_MINUTE: (SHORT: 'წ', LONG: 'წუთი'),
      MINUTES: (SHORT: 'წ', LONG: 'წუთი'),
      ONE_HOUR: (SHORT: 'სთ', LONG: 'საათი'),
      HOURS: (SHORT: 'სთ', LONG: 'საათი'),
      ONE_DAY: (SHORT: 'დ', LONG: 'დღე'),
      DAYS: (SHORT: 'დ', LONG: 'დღე'),
      ONE_MONTH: (SHORT: 'თ', LONG: 'თვე'),
      MONTHS: (SHORT: 'თ', LONG: 'თვე'),
      SUFFIX: (SHORT: 'წინ', LONG: 'წინ'),
      ONE_YEAR: (SHORT: 'წ', LONG: 'წელი'),
      YEARS: (SHORT: 'წ', LONG: 'წელი'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'kk': TimeagoSymbol(
      JUST_NOW: (SHORT: 'қазір', LONG: 'қазір'),
      SECONDS: (SHORT: 'с', LONG: 'секунд'),
      ONE_MINUTE: (SHORT: 'м', LONG: 'минут'),
      MINUTES: (SHORT: 'м', LONG: 'минут'),
      ONE_HOUR: (SHORT: 'с', LONG: 'сағат'),
      HOURS: (SHORT: 'с', LONG: 'сағат'),
      ONE_DAY: (SHORT: 'к', LONG: 'күн'),
      DAYS: (SHORT: 'к', LONG: 'күн'),
      ONE_MONTH: (SHORT: 'ай', LONG: 'ай'),
      MONTHS: (SHORT: 'ай', LONG: 'ай'),
      SUFFIX: (SHORT: 'бұрын', LONG: 'бұрын'),
      ONE_YEAR: (SHORT: 'ж', LONG: 'жыл'),
      YEARS: (SHORT: 'ж', LONG: 'жыл'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'km': TimeagoSymbol(
      JUST_NOW: (SHORT: 'ឥឡូវនេះ', LONG: 'ឥឡូវនេះ'),
      SECONDS: (SHORT: 'វ', LONG: 'វិនាទី'),
      ONE_MINUTE: (SHORT: 'ន', LONG: 'នាទី'),
      MINUTES: (SHORT: 'ន', LONG: 'នាទី'),
      ONE_HOUR: (SHORT: 'ម', LONG: 'ម៉ោង'),
      HOURS: (SHORT: 'ម', LONG: 'ម៉ោង'),
      ONE_DAY: (SHORT: 'ថ្ងៃ', LONG: 'ថ្ងៃ'),
      DAYS: (SHORT: 'ថ្ងៃ', LONG: 'ថ្ងៃ'),
      ONE_MONTH: (SHORT: 'ខ', LONG: 'ខែ'),
      MONTHS: (SHORT: 'ខ', LONG: 'ខែ'),
      SUFFIX: (SHORT: 'មួយកាលមុន', LONG: 'មួយកាលមុន'),
      ONE_YEAR: (SHORT: 'ឆ', LONG: 'ឆ្នាំ'),
      YEARS: (SHORT: 'ឆ', LONG: 'ឆ្នាំ'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'kn': TimeagoSymbol(
      JUST_NOW: (SHORT: 'ಈಗಲೇ', LONG: 'ಈಗಲೇ'),
      SECONDS: (SHORT: 'ಸೆಕೆಂಡು', LONG: 'ಸೆಕೆಂಡು'),
      ONE_MINUTE: (SHORT: 'ನಿಮಿ', LONG: 'ನಿಮಿಷ'),
      MINUTES: (SHORT: 'ನಿಮಿ', LONG: 'ನಿಮಿಷ'),
      ONE_HOUR: (SHORT: 'ಗಂಟೆ', LONG: 'ಗಂಟೆ'),
      HOURS: (SHORT: 'ಗಂಟೆ', LONG: 'ಗಂಟೆ'),
      ONE_DAY: (SHORT: 'ದಿನ', LONG: 'ದಿನ'),
      DAYS: (SHORT: 'ದಿನ', LONG: 'ದಿನ'),
      ONE_MONTH: (SHORT: 'ತಿಂಗಳು', LONG: 'ತಿಂಗಳು'),
      MONTHS: (SHORT: 'ತಿಂಗಳು', LONG: 'ತಿಂಗಳು'),
      SUFFIX: (SHORT: 'ಹಿಂದೆ', LONG: 'ಹಿಂದೆ'),
      ONE_YEAR: (SHORT: 'ವರ್ಷ', LONG: 'ವರ್ಷ'),
      YEARS: (SHORT: 'ವರ್ಷ', LONG: 'ವರ್ಷ'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'ko': TimeagoSymbol(
      JUST_NOW: (SHORT: '지금', LONG: '방금'),
      SECONDS: (SHORT: '초', LONG: '초'),
      ONE_MINUTE: (SHORT: '분', LONG: '분'),
      MINUTES: (SHORT: '분', LONG: '분'),
      ONE_HOUR: (SHORT: '시간', LONG: '시간'),
      HOURS: (SHORT: '시간', LONG: '시간'),
      ONE_DAY: (SHORT: '일', LONG: '일'),
      DAYS: (SHORT: '일', LONG: '일'),
      ONE_MONTH: (SHORT: '개월', LONG: '개월'),
      MONTHS: (SHORT: '개월', LONG: '개월'),
      SUFFIX: (SHORT: '전', LONG: '전'),
      ONE_YEAR: (SHORT: '년', LONG: '년'),
      YEARS: (SHORT: '년', LONG: '년'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'ky': TimeagoSymbol(
      JUST_NOW: (SHORT: 'азыр', LONG: 'азыр'),
      SECONDS: (SHORT: 'с', LONG: 'секунд'),
      ONE_MINUTE: (SHORT: 'м', LONG: 'минут'),
      MINUTES: (SHORT: 'м', LONG: 'минут'),
      ONE_HOUR: (SHORT: 'с', LONG: 'саат'),
      HOURS: (SHORT: 'с', LONG: 'саат'),
      ONE_DAY: (SHORT: 'к', LONG: 'күн'),
      DAYS: (SHORT: 'к', LONG: 'күн'),
      ONE_MONTH: (SHORT: 'ай', LONG: 'ай'),
      MONTHS: (SHORT: 'ай', LONG: 'ай'),
      SUFFIX: (SHORT: 'бұрын', LONG: 'бұрын'),
      ONE_YEAR: (SHORT: 'ж', LONG: 'жыл'),
      YEARS: (SHORT: 'ж', LONG: 'жыл'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'ln': TimeagoSymbol(
      JUST_NOW: (SHORT: 'soki', LONG: 'soki'),
      SECONDS: (SHORT: 's', LONG: 'segónde'),
      ONE_MINUTE: (SHORT: 'm', LONG: 'minúte'),
      MINUTES: (SHORT: 'm', LONG: 'minúte'),
      ONE_HOUR: (SHORT: 'h', LONG: 'lɛ́ngɔ́'),
      HOURS: (SHORT: 'h', LONG: 'lɛ́ngɔ́'),
      ONE_DAY: (SHORT: 'j', LONG: 'sángó'),
      DAYS: (SHORT: 'j', LONG: 'sángó'),
      ONE_MONTH: (SHORT: 'm', LONG: 'sánzá'),
      MONTHS: (SHORT: 'm', LONG: 'sánzá'),
      SUFFIX: (SHORT: 'moko', LONG: 'moko'),
      ONE_YEAR: (SHORT: 'y', LONG: 'mwaaka'),
      YEARS: (SHORT: 'y', LONG: 'mwaaka'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'lo': TimeagoSymbol(
      JUST_NOW: (SHORT: 'ຕອນນີ້', LONG: 'ຕອນນີ້'),
      SECONDS: (SHORT: 'ວ', LONG: 'ວິນາທີ'),
      ONE_MINUTE: (SHORT: 'ນ', LONG: 'ນາທີ'),
      MINUTES: (SHORT: 'ນ', LONG: 'ນາທີ'),
      ONE_HOUR: (SHORT: 'ຊ', LONG: 'ຊົ່ວໂມງ'),
      HOURS: (SHORT: 'ຊ', LONG: 'ຊົ່ວໂມງ'),
      ONE_DAY: (SHORT: 'ມ', LONG: 'ມື້'),
      DAYS: (SHORT: 'ມ', LONG: 'ມື້'),
      ONE_MONTH: (SHORT: 'ເ', LONG: 'ເດືອນ'),
      MONTHS: (SHORT: 'ເ', LONG: 'ເດືອນ'),
      SUFFIX: (SHORT: 'ຜ່ານມາ', LONG: 'ຜ່ານມາ'),
      ONE_YEAR: (SHORT: 'ປ', LONG: 'ປີ'),
      YEARS: (SHORT: 'ປ', LONG: 'ປີ'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'lt': TimeagoSymbol(
      JUST_NOW: (SHORT: 'dabar', LONG: 'būtent dabar'),
      SECONDS: (SHORT: 's', LONG: 'sekundė'),
      ONE_MINUTE: (SHORT: 'min', LONG: 'minutė'),
      MINUTES: (SHORT: 'min', LONG: 'minutės'),
      ONE_HOUR: (SHORT: 'val', LONG: 'valanda'),
      HOURS: (SHORT: 'val', LONG: 'valandos'),
      ONE_DAY: (SHORT: 'd', LONG: 'diena'),
      DAYS: (SHORT: 'd', LONG: 'dienos'),
      ONE_MONTH: (SHORT: 'mėn', LONG: 'mėnuo'),
      MONTHS: (SHORT: 'mėn', LONG: 'mėnesiai'),
      SUFFIX: (SHORT: 'prieš', LONG: 'prieš'),
      ONE_YEAR: (SHORT: 'm', LONG: 'metai'),
      YEARS: (SHORT: 'm', LONG: 'metai'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'lv': TimeagoSymbol(
      JUST_NOW: (SHORT: 'tagad', LONG: 'tikko tagad'),
      SECONDS: (SHORT: 's', LONG: 'sekunde'),
      ONE_MINUTE: (SHORT: 'min', LONG: 'minūte'),
      MINUTES: (SHORT: 'min', LONG: 'minūtes'),
      ONE_HOUR: (SHORT: 'st', LONG: 'stunda'),
      HOURS: (SHORT: 'st', LONG: 'stundas'),
      ONE_DAY: (SHORT: 'd', LONG: 'diena'),
      DAYS: (SHORT: 'd', LONG: 'dienas'),
      ONE_MONTH: (SHORT: 'mēn', LONG: 'mēnesis'),
      MONTHS: (SHORT: 'mēn', LONG: 'mēneši'),
      SUFFIX: (SHORT: 'atpakaļ', LONG: 'atpakaļ'),
      ONE_YEAR: (SHORT: 'g', LONG: 'gads'),
      YEARS: (SHORT: 'g', LONG: 'gadi'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'mg': TimeagoSymbol(
      JUST_NOW: (SHORT: 'taom', LONG: 'taom-baovao'),
      SECONDS: (SHORT: 's', LONG: 'segondra'),
      ONE_MINUTE: (SHORT: 'm', LONG: 'minitra'),
      MINUTES: (SHORT: 'm', LONG: 'minitra'),
      ONE_HOUR: (SHORT: 'h', LONG: 'ora'),
      HOURS: (SHORT: 'h', LONG: 'ora'),
      ONE_DAY: (SHORT: 'andro', LONG: 'andro'),
      DAYS: (SHORT: 'andro', LONG: 'andro'),
      ONE_MONTH: (SHORT: 'volana', LONG: 'volana'),
      MONTHS: (SHORT: 'volana', LONG: 'volana'),
      SUFFIX: (SHORT: 'lasa', LONG: 'lasa'),
      ONE_YEAR: (SHORT: 'taona', LONG: 'taona'),
      YEARS: (SHORT: 'taona', LONG: 'taona'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'mk': TimeagoSymbol(
      JUST_NOW: (SHORT: 'сега', LONG: 'токму сега'),
      SECONDS: (SHORT: 'с', LONG: 'секунда'),
      ONE_MINUTE: (SHORT: 'м', LONG: 'минута'),
      MINUTES: (SHORT: 'м', LONG: 'минути'),
      ONE_HOUR: (SHORT: 'ч', LONG: 'час'),
      HOURS: (SHORT: 'ч', LONG: 'часа'),
      ONE_DAY: (SHORT: 'д', LONG: 'ден'),
      DAYS: (SHORT: 'д', LONG: 'дена'),
      ONE_MONTH: (SHORT: 'мес', LONG: 'месец'),
      MONTHS: (SHORT: 'мес', LONG: 'месеци'),
      SUFFIX: (SHORT: 'пред', LONG: 'пред'),
      ONE_YEAR: (SHORT: 'г', LONG: 'година'),
      YEARS: (SHORT: 'г', LONG: 'години'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'ml': TimeagoSymbol(
      JUST_NOW: (SHORT: 'ഇപ്പോള്‍', LONG: 'ഇപ്പോള്‍'),
      SECONDS: (SHORT: 'സെ', LONG: 'സെക്കന്റ്'),
      ONE_MINUTE: (SHORT: 'മി', LONG: 'മിനിറ്റ്'),
      MINUTES: (SHORT: 'മി', LONG: 'മിനിറ്റ്'),
      ONE_HOUR: (SHORT: 'മ', LONG: 'മണിക്കൂറ്'),
      HOURS: (SHORT: 'മ', LONG: 'മണിക്കൂറ്'),
      ONE_DAY: (SHORT: 'ദി', LONG: 'ദിവസം'),
      DAYS: (SHORT: 'ദി', LONG: 'ദിവസങ്ങള്‍'),
      ONE_MONTH: (SHORT: 'മാ', LONG: 'മാസം'),
      MONTHS: (SHORT: 'മാ', LONG: 'മാസങ്ങള്‍'),
      SUFFIX: (SHORT: 'മുമ്പ്', LONG: 'മുമ്പ്'),
      ONE_YEAR: (SHORT: 'വ', LONG: 'വര്‍ഷം'),
      YEARS: (SHORT: 'വ', LONG: 'വര്‍ഷങ്ങള്‍'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'mn': TimeagoSymbol(
      JUST_NOW: (SHORT: 'одоо', LONG: 'одоогоор'),
      SECONDS: (SHORT: 'с', LONG: 'секунд'),
      ONE_MINUTE: (SHORT: 'мин', LONG: 'минут'),
      MINUTES: (SHORT: 'мин', LONG: 'минут'),
      ONE_HOUR: (SHORT: 'цаг', LONG: 'цаг'),
      HOURS: (SHORT: 'цаг', LONG: 'цаг'),
      ONE_DAY: (SHORT: 'өдөр', LONG: 'өдөр'),
      DAYS: (SHORT: 'өдөр', LONG: 'өдөр'),
      ONE_MONTH: (SHORT: 'сар', LONG: 'сар'),
      MONTHS: (SHORT: 'сар', LONG: 'сар'),
      SUFFIX: (SHORT: 'өмнө', LONG: 'өмнө'),
      ONE_YEAR: (SHORT: 'жил', LONG: 'жил'),
      YEARS: (SHORT: 'жил', LONG: 'жил'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'mr': TimeagoSymbol(
      JUST_NOW: (SHORT: 'आता', LONG: 'आता'),
      SECONDS: (SHORT: 'से', LONG: 'सेकंड'),
      ONE_MINUTE: (SHORT: 'मि', LONG: 'मिनिट'),
      MINUTES: (SHORT: 'मि', LONG: 'मिनिट'),
      ONE_HOUR: (SHORT: 'ता', LONG: 'तास'),
      HOURS: (SHORT: 'ता', LONG: 'तास'),
      ONE_DAY: (SHORT: 'दि', LONG: 'दिवस'),
      DAYS: (SHORT: 'दि', LONG: 'दिवस'),
      ONE_MONTH: (SHORT: 'मही', LONG: 'महिना'),
      MONTHS: (SHORT: 'मही', LONG: 'महिना'),
      SUFFIX: (SHORT: 'पूर्वी', LONG: 'पूर्वी'),
      ONE_YEAR: (SHORT: 'वर्ष', LONG: 'वर्ष'),
      YEARS: (SHORT: 'वर्ष', LONG: 'वर्ष'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'ms': TimeagoSymbol(
      JUST_NOW: (SHORT: 'baru saja', LONG: 'baru saja'),
      SECONDS: (SHORT: 'd', LONG: 'detik'),
      ONE_MINUTE: (SHORT: 'm', LONG: 'minit'),
      MINUTES: (SHORT: 'm', LONG: 'minit'),
      ONE_HOUR: (SHORT: 'j', LONG: 'jam'),
      HOURS: (SHORT: 'j', LONG: 'jam'),
      ONE_DAY: (SHORT: 'h', LONG: 'hari'),
      DAYS: (SHORT: 'h', LONG: 'hari'),
      ONE_MONTH: (SHORT: 'b', LONG: 'bulan'),
      MONTHS: (SHORT: 'b', LONG: 'bulan'),
      SUFFIX: (SHORT: 'yang lalu', LONG: 'yang lalu'),
      ONE_YEAR: (SHORT: 't', LONG: 'tahun'),
      YEARS: (SHORT: 't', LONG: 'tahun'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'mt': TimeagoSymbol(
      JUST_NOW: (SHORT: 'dak', LONG: 'dak'),
      SECONDS: (SHORT: 's', LONG: 'sekondi'),
      ONE_MINUTE: (SHORT: 'm', LONG: 'minuta'),
      MINUTES: (SHORT: 'm', LONG: 'minuti'),
      ONE_HOUR: (SHORT: 's', LONG: 'siegħa'),
      HOURS: (SHORT: 's', LONG: 'sieħat'),
      ONE_DAY: (SHORT: 'j', LONG: 'jum'),
      DAYS: (SHORT: 'j', LONG: 'jiem'),
      ONE_MONTH: (SHORT: 'x', LONG: 'xahar'),
      MONTHS: (SHORT: 'x', LONG: 'xhur'),
      SUFFIX: (SHORT: 'ilu', LONG: 'ilu'),
      ONE_YEAR: (SHORT: 's', LONG: 'sena'),
      YEARS: (SHORT: 's', LONG: 'snin'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'my': TimeagoSymbol(
      JUST_NOW: (SHORT: 'ယခု', LONG: 'ယခုအတွင်း'),
      SECONDS: (SHORT: 'စ', LONG: 'စက္ကန့်'),
      ONE_MINUTE: (SHORT: 'မ', LONG: 'မိနစ်'),
      MINUTES: (SHORT: 'မ', LONG: 'မိနစ်'),
      ONE_HOUR: (SHORT: 'န', LONG: 'နာရီ'),
      HOURS: (SHORT: 'န', LONG: 'နာရီ'),
      ONE_DAY: (SHORT: 'ရက်', LONG: 'ရက်'),
      DAYS: (SHORT: 'ရက်', LONG: 'ရက်'),
      ONE_MONTH: (SHORT: 'လ', LONG: 'လ'),
      MONTHS: (SHORT: 'လ', LONG: 'လ'),
      SUFFIX: (SHORT: 'အတွင်း', LONG: 'အတွင်း'),
      ONE_YEAR: (SHORT: 'န', LONG: 'နှစ်'),
      YEARS: (SHORT: 'န', LONG: 'နှစ်'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'nb': TimeagoSymbol(
      JUST_NOW: (SHORT: 'nå', LONG: 'akkurat nå'),
      SECONDS: (SHORT: 's', LONG: 'sekund'),
      ONE_MINUTE: (SHORT: 'm', LONG: 'minutt'),
      MINUTES: (SHORT: 'm', LONG: 'minutter'),
      ONE_HOUR: (SHORT: 't', LONG: 'time'),
      HOURS: (SHORT: 't', LONG: 'timer'),
      ONE_DAY: (SHORT: 'd', LONG: 'dag'),
      DAYS: (SHORT: 'd', LONG: 'dager'),
      ONE_MONTH: (SHORT: 'mnd', LONG: 'måned'),
      MONTHS: (SHORT: 'mnd', LONG: 'måneder'),
      SUFFIX: (SHORT: 'siden', LONG: 'siden'),
      ONE_YEAR: (SHORT: 'år', LONG: 'år'),
      YEARS: (SHORT: 'år', LONG: 'år'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'ne': TimeagoSymbol(
      JUST_NOW: (SHORT: 'अभिमुखी', LONG: 'अब'),
      SECONDS: (SHORT: 'से', LONG: 'सेकेण्ड'),
      ONE_MINUTE: (SHORT: 'मि', LONG: 'मिनेट'),
      MINUTES: (SHORT: 'मि', LONG: 'मिनेटहरू'),
      ONE_HOUR: (SHORT: 'घ', LONG: 'घण्टा'),
      HOURS: (SHORT: 'घ', LONG: 'घण्टाहरू'),
      ONE_DAY: (SHORT: 'दिन', LONG: 'दिन'),
      DAYS: (SHORT: 'दिन', LONG: 'दिनहरू'),
      ONE_MONTH: (SHORT: 'मह', LONG: 'महिना'),
      MONTHS: (SHORT: 'मह', LONG: 'महिनाहरू'),
      SUFFIX: (SHORT: 'अघि', LONG: 'अघि'),
      ONE_YEAR: (SHORT: 'वर्ष', LONG: 'वर्ष'),
      YEARS: (SHORT: 'वर्ष', LONG: 'वर्षहरू'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'nl': TimeagoSymbol(
      JUST_NOW: (SHORT: 'nu', LONG: 'zojuist'),
      SECONDS: (SHORT: 's', LONG: 'seconde'),
      ONE_MINUTE: (SHORT: 'm', LONG: 'minuut'),
      MINUTES: (SHORT: 'm', LONG: 'minuten'),
      ONE_HOUR: (SHORT: 'u', LONG: 'uur'),
      HOURS: (SHORT: 'u', LONG: 'uur'),
      ONE_DAY: (SHORT: 'd', LONG: 'dag'),
      DAYS: (SHORT: 'd', LONG: 'dagen'),
      ONE_MONTH: (SHORT: 'mnd', LONG: 'maand'),
      MONTHS: (SHORT: 'mnd', LONG: 'maanden'),
      SUFFIX: (SHORT: 'geleden', LONG: 'geleden'),
      ONE_YEAR: (SHORT: 'j', LONG: 'jaar'),
      YEARS: (SHORT: 'j', LONG: 'jaar'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'no': TimeagoSymbol(
      JUST_NOW: (SHORT: 'nå', LONG: 'akkurat nå'),
      SECONDS: (SHORT: 's', LONG: 'sekund'),
      ONE_MINUTE: (SHORT: 'm', LONG: 'minutt'),
      MINUTES: (SHORT: 'm', LONG: 'minutter'),
      ONE_HOUR: (SHORT: 't', LONG: 'time'),
      HOURS: (SHORT: 't', LONG: 'timer'),
      ONE_DAY: (SHORT: 'd', LONG: 'dag'),
      DAYS: (SHORT: 'd', LONG: 'dager'),
      ONE_MONTH: (SHORT: 'mnd', LONG: 'måned'),
      MONTHS: (SHORT: 'mnd', LONG: 'måneder'),
      SUFFIX: (SHORT: 'siden', LONG: 'siden'),
      ONE_YEAR: (SHORT: 'år', LONG: 'år'),
      YEARS: (SHORT: 'år', LONG: 'år'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'no_NO': TimeagoSymbol(
      JUST_NOW: (SHORT: 'nå', LONG: 'akkurat nå'),
      SECONDS: (SHORT: 's', LONG: 'sekund'),
      ONE_MINUTE: (SHORT: 'm', LONG: 'minutt'),
      MINUTES: (SHORT: 'm', LONG: 'minutter'),
      ONE_HOUR: (SHORT: 't', LONG: 'time'),
      HOURS: (SHORT: 't', LONG: 'timer'),
      ONE_DAY: (SHORT: 'd', LONG: 'dag'),
      DAYS: (SHORT: 'd', LONG: 'dager'),
      ONE_MONTH: (SHORT: 'mnd', LONG: 'måned'),
      MONTHS: (SHORT: 'mnd', LONG: 'måneder'),
      SUFFIX: (SHORT: 'siden', LONG: 'siden'),
      ONE_YEAR: (SHORT: 'år', LONG: 'år'),
      YEARS: (SHORT: 'år', LONG: 'år'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'nyn': TimeagoSymbol(
        JUST_NOW: (SHORT: 'nettopp', LONG: 'akkurat nå'),
        SECONDS: (SHORT: 'sek', LONG: 'sekunder'),
        ONE_MINUTE: (SHORT: 'm', LONG: 'ett minutt'),
        MINUTES: (SHORT: 'min', LONG: 'minutter'),
        ONE_HOUR: (SHORT: 't', LONG: 'en time'),
        HOURS: (SHORT: 't', LONG: 'timer'),
        ONE_DAY: (SHORT: 'd', LONG: 'en dag'),
        DAYS: (SHORT: 'd', LONG: 'dager'),
        ONE_MONTH: (SHORT: 'mnd', LONG: 'en måned'),
        MONTHS: (SHORT: 'mnd', LONG: 'måneder'),
        SUFFIX: (SHORT: 'siden', LONG: 'siden'),
        ONE_YEAR: (SHORT: 'år', LONG: 'ett år'),
        YEARS: (SHORT: 'år', LONG: 'år'),
        SEPARATOR: (SHORT: ' ', LONG: ' ')),
    'or': TimeagoSymbol(
        JUST_NOW: (SHORT: ' अभी', LONG: ' अभी'),
        SECONDS: (SHORT: 'सेकेंड', LONG: 'सेकेंड'),
        ONE_MINUTE: (SHORT: 'मिनट', LONG: 'एक मिनट'),
        MINUTES: (SHORT: 'मिनट', LONG: 'मिनट'),
        ONE_HOUR: (SHORT: 'घंटा', LONG: 'एक घंटा'),
        HOURS: (SHORT: 'घंटा', LONG: 'घंटा'),
        ONE_DAY: (SHORT: 'दिन', LONG: 'एक दिन'),
        DAYS: (SHORT: 'दिन', LONG: 'दिन'),
        ONE_MONTH: (SHORT: 'मास', LONG: 'एक मास'),
        MONTHS: (SHORT: 'मास', LONG: 'मास'),
        SUFFIX: (SHORT: 'पहिले', LONG: 'पहिले'),
        ONE_YEAR: (SHORT: 'वर्ष', LONG: 'एक वर्ष'),
        YEARS: (SHORT: 'वर्ष', LONG: 'वर्ष'),
        SEPARATOR: (SHORT: ' ', LONG: ' ')),
    'pa': TimeagoSymbol(
      JUST_NOW: (SHORT: 'ਹੁਣੇ ਹੀ', LONG: 'ਹੁਣੇ ਹੀ'),
      SECONDS: (SHORT: 'ਸਕਿੰਟ', LONG: 'ਸਕਿੰਟ'),
      ONE_MINUTE: (SHORT: 'ਮਿੰਟ', LONG: 'ਇੱਕ ਮਿੰਟ'),
      MINUTES: (SHORT: 'ਮਿੰਟ', LONG: 'ਮਿੰਟ'),
      ONE_HOUR: (SHORT: 'ਘੰਟਾ', LONG: 'ਇੱਕ ਘੰਟਾ'),
      HOURS: (SHORT: 'ਘੰਟਾ', LONG: 'ਘੰਟੇ'),
      ONE_DAY: (SHORT: 'ਦਿਨ', LONG: 'ਇੱਕ ਦਿਨ'),
      DAYS: (SHORT: 'ਦਿਨ', LONG: 'ਦਿਨ'),
      ONE_MONTH: (SHORT: 'ਮਹੀਨਾ', LONG: 'ਇੱਕ ਮਹੀਨਾ'),
      MONTHS: (SHORT: 'ਮਹੀਨਾ', LONG: 'ਮਹੀਨੇ'),
      SUFFIX: (SHORT: 'ਪਹਿਲਾਂ', LONG: 'ਪਹਿਲਾਂ'),
      ONE_YEAR: (SHORT: 'ਸਾਲ', LONG: 'ਇੱਕ ਸਾਲ'),
      YEARS: (SHORT: 'ਸਾਲ', LONG: 'ਸਾਲ'),
      SEPARATOR: (SHORT: ' ', LONG: ' '),
    ),
    'pl': TimeagoSymbol(
      JUST_NOW: (SHORT: 'właśnie', LONG: 'właśnie teraz'),
      SECONDS: (SHORT: 'sek', LONG: 'sekund'),
      ONE_MINUTE: (SHORT: 'min', LONG: 'minut'),
      MINUTES: (SHORT: 'min', LONG: 'minut'),
      ONE_HOUR: (SHORT: 'godz', LONG: 'jedna godzina'),
      HOURS: (SHORT: 'godz', LONG: 'godzin'),
      ONE_DAY: (SHORT: 'd', LONG: 'jeden dzień'),
      DAYS: (SHORT: 'd', LONG: 'dni'),
      ONE_MONTH: (SHORT: 'mies', LONG: 'jeden miesiąc'),
      MONTHS: (SHORT: 'mies', LONG: 'miesięcy'),
      SUFFIX: (SHORT: 'temu', LONG: 'temu'),
      ONE_YEAR: (SHORT: 'rok', LONG: 'jeden rok'),
      YEARS: (SHORT: 'rok', LONG: 'lat'),
      SEPARATOR: (SHORT: ' ', LONG: ' '),
    ),
    'sk': TimeagoSymbol(
        JUST_NOW: (SHORT: 'práve teraz', LONG: 'práve teraz'),
        SECONDS: (SHORT: 'sek', LONG: 'sekúnd'),
        ONE_MINUTE: (SHORT: 'm', LONG: 'jedna minúta'),
        MINUTES: (SHORT: 'min', LONG: 'minút'),
        ONE_HOUR: (SHORT: 'h', LONG: 'jedna hodina'),
        HOURS: (SHORT: 'h', LONG: 'hodín'),
        ONE_DAY: (SHORT: 'd', LONG: 'jeden deň'),
        DAYS: (SHORT: 'd', LONG: 'dní'),
        ONE_MONTH: (SHORT: 'mesiac', LONG: 'jeden mesiac'),
        MONTHS: (SHORT: 'mes', LONG: 'mesiacov'),
        SUFFIX: (SHORT: 'pred', LONG: 'pred'),
        ONE_YEAR: (SHORT: 'rok', LONG: 'jeden rok'),
        YEARS: (SHORT: 'r', LONG: 'rokov'),
        SEPARATOR: (SHORT: ' ', LONG: ' ')),
    'si': TimeagoSymbol(
      JUST_NOW: (SHORT: 'මේ זהාම අවස්ථාවේ', LONG: 'මේ זהාම අවස්ථාවේ'),
      SECONDS: (SHORT: 'තත්පර', LONG: 'තත්පර කිහෙబ'),
      ONE_MINUTE: (SHORT: 'මින', LONG: 'මිනුත්තක්'),
      MINUTES: (SHORT: 'මින', LONG: 'මිනුත්තු'),
      ONE_HOUR: (SHORT: 'පැය', LONG: 'පැයක්'),
      HOURS: (SHORT: 'පැය', LONG: 'පැය'),
      ONE_DAY: (SHORT: 'දවස', LONG: 'දවසක්'),
      DAYS: (SHORT: 'දවස', LONG: 'දවස්'),
      ONE_MONTH: (SHORT: 'මාසය', LONG: 'මාසයක්'),
      MONTHS: (SHORT: 'මාස', LONG: 'මාස'),
      SUFFIX: (SHORT: 'කට', LONG: 'කට පෙර'),
      ONE_YEAR: (SHORT: 'වර්ෂය', LONG: 'වර්ෂයක්'),
      YEARS: (SHORT: 'වර්ෂ', LONG: 'වර්ෂ'),
      SEPARATOR: (SHORT: ' ', LONG: ' '),
    ),
    'ps': TimeagoSymbol(
      JUST_NOW: (SHORT: 'همین', LONG: 'فوراً'),
      SECONDS: (SHORT: 'ثانیه', LONG: 'ثانیه'),
      ONE_MINUTE: (SHORT: 'د', LONG: 'دقیقه'),
      MINUTES: (SHORT: 'د', LONG: 'دقایق'),
      ONE_HOUR: (SHORT: 'س', LONG: 'ساعت'),
      HOURS: (SHORT: 'س', LONG: 'ساعات'),
      ONE_DAY: (SHORT: 'و', LONG: 'ورځ'),
      DAYS: (SHORT: 'و', LONG: 'ورځې'),
      ONE_MONTH: (SHORT: 'م', LONG: 'میاشت'),
      MONTHS: (SHORT: 'م', LONG: 'میاشتونه'),
      SUFFIX: (SHORT: 'پخوانی', LONG: 'پخوا'),
      ONE_YEAR: (SHORT: 'زوړه', LONG: 'زوړه'),
      YEARS: (SHORT: 'زوړه', LONG: 'زوړه'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'pt': TimeagoSymbol(
      JUST_NOW: (SHORT: 'agora', LONG: 'agora mesmo'),
      SECONDS: (SHORT: 's', LONG: 'segundo'),
      ONE_MINUTE: (SHORT: 'm', LONG: 'minuto'),
      MINUTES: (SHORT: 'm', LONG: 'minutos'),
      ONE_HOUR: (SHORT: 'h', LONG: 'hora'),
      HOURS: (SHORT: 'h', LONG: 'horas'),
      ONE_DAY: (SHORT: 'd', LONG: 'dia'),
      DAYS: (SHORT: 'd', LONG: 'dias'),
      ONE_MONTH: (SHORT: 'mês', LONG: 'mês'),
      MONTHS: (SHORT: 'mês', LONG: 'meses'),
      SUFFIX: (SHORT: 'atrás', LONG: 'atrás'),
      ONE_YEAR: (SHORT: 'ano', LONG: 'ano'),
      YEARS: (SHORT: 'ano', LONG: 'anos'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'pt_BR': TimeagoSymbol(
      JUST_NOW: (SHORT: 'agora', LONG: 'agora mesmo'),
      SECONDS: (SHORT: 's', LONG: 'segundo'),
      ONE_MINUTE: (SHORT: 'm', LONG: 'minuto'),
      MINUTES: (SHORT: 'm', LONG: 'minutos'),
      ONE_HOUR: (SHORT: 'h', LONG: 'hora'),
      HOURS: (SHORT: 'h', LONG: 'horas'),
      ONE_DAY: (SHORT: 'd', LONG: 'dia'),
      DAYS: (SHORT: 'd', LONG: 'dias'),
      ONE_MONTH: (SHORT: 'mês', LONG: 'mês'),
      MONTHS: (SHORT: 'mês', LONG: 'meses'),
      SUFFIX: (SHORT: 'atrás', LONG: 'atrás'),
      ONE_YEAR: (SHORT: 'ano', LONG: 'ano'),
      YEARS: (SHORT: 'ano', LONG: 'anos'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'pt_PT': TimeagoSymbol(
      JUST_NOW: (SHORT: 'agora', LONG: 'agora mesmo'),
      SECONDS: (SHORT: 's', LONG: 'segundo'),
      ONE_MINUTE: (SHORT: 'm', LONG: 'minuto'),
      MINUTES: (SHORT: 'm', LONG: 'minutos'),
      ONE_HOUR: (SHORT: 'h', LONG: 'hora'),
      HOURS: (SHORT: 'h', LONG: 'horas'),
      ONE_DAY: (SHORT: 'd', LONG: 'dia'),
      DAYS: (SHORT: 'd', LONG: 'dias'),
      ONE_MONTH: (SHORT: 'mês', LONG: 'mês'),
      MONTHS: (SHORT: 'mês', LONG: 'meses'),
      SUFFIX: (SHORT: 'atrás', LONG: 'atrás'),
      ONE_YEAR: (SHORT: 'ano', LONG: 'ano'),
      YEARS: (SHORT: 'ano', LONG: 'anos'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'ro': TimeagoSymbol(
      JUST_NOW: (SHORT: 'acum', LONG: 'chiar acum'),
      SECONDS: (SHORT: 's', LONG: 'secundă'),
      ONE_MINUTE: (SHORT: 'm', LONG: 'minut'),
      MINUTES: (SHORT: 'm', LONG: 'minute'),
      ONE_HOUR: (SHORT: 'h', LONG: 'oră'),
      HOURS: (SHORT: 'h', LONG: 'ore'),
      ONE_DAY: (SHORT: 'zi', LONG: 'zi'),
      DAYS: (SHORT: 'zi', LONG: 'zile'),
      ONE_MONTH: (SHORT: 'lună', LONG: 'lună'),
      MONTHS: (SHORT: 'luni', LONG: 'luni'),
      SUFFIX: (SHORT: 'în urmă', LONG: 'în urmă'),
      ONE_YEAR: (SHORT: 'an', LONG: 'an'),
      YEARS: (SHORT: 'ani', LONG: 'ani'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'ru': TimeagoSymbol(
      JUST_NOW: (SHORT: 'сейчас', LONG: 'только что'),
      SECONDS: (SHORT: 'с', LONG: 'секунда'),
      ONE_MINUTE: (SHORT: 'м', LONG: 'минута'),
      MINUTES: (SHORT: 'м', LONG: 'минуты'),
      ONE_HOUR: (SHORT: 'ч', LONG: 'час'),
      HOURS: (SHORT: 'ч', LONG: 'часа'),
      ONE_DAY: (SHORT: 'д', LONG: 'день'),
      DAYS: (SHORT: 'д', LONG: 'дня'),
      ONE_MONTH: (SHORT: 'м', LONG: 'месяц'),
      MONTHS: (SHORT: 'м', LONG: 'месяца'),
      SUFFIX: (SHORT: 'назад', LONG: 'назад'),
      ONE_YEAR: (SHORT: 'г', LONG: 'год'),
      YEARS: (SHORT: 'г', LONG: 'года'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'sl': TimeagoSymbol(
      JUST_NOW: (SHORT: 'zdaj', LONG: 'ravno zdaj'),
      SECONDS: (SHORT: 's', LONG: 'sekunda'),
      ONE_MINUTE: (SHORT: 'm', LONG: 'minuta'),
      MINUTES: (SHORT: 'm', LONG: 'minute'),
      ONE_HOUR: (SHORT: 'h', LONG: 'ura'),
      HOURS: (SHORT: 'h', LONG: 'ure'),
      ONE_DAY: (SHORT: 'd', LONG: 'dan'),
      DAYS: (SHORT: 'd', LONG: 'dni'),
      ONE_MONTH: (SHORT: 'm', LONG: 'mesec'),
      MONTHS: (SHORT: 'm', LONG: 'mesece'),
      SUFFIX: (SHORT: 'nazaj', LONG: 'nazaj'),
      ONE_YEAR: (SHORT: 'l', LONG: 'leto'),
      YEARS: (SHORT: 'l', LONG: 'leta'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'sq': TimeagoSymbol(
      JUST_NOW: (SHORT: 'tani', LONG: 'tani në këtë moment'),
      SECONDS: (SHORT: 's', LONG: 'sekondë'),
      ONE_MINUTE: (SHORT: 'min', LONG: 'minutë'),
      MINUTES: (SHORT: 'min', LONG: 'minuta'),
      ONE_HOUR: (SHORT: 'orë', LONG: 'orë'),
      HOURS: (SHORT: 'orë', LONG: 'orë'),
      ONE_DAY: (SHORT: 'ditë', LONG: 'ditë'),
      DAYS: (SHORT: 'ditë', LONG: 'ditë'),
      ONE_MONTH: (SHORT: 'muaj', LONG: 'muaj'),
      MONTHS: (SHORT: 'muaj', LONG: 'muaj'),
      SUFFIX: (SHORT: 'më parë', LONG: 'më parë'),
      ONE_YEAR: (SHORT: 'vit', LONG: 'vit'),
      YEARS: (SHORT: 'vjet', LONG: 'vjet'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'sr': TimeagoSymbol(
      JUST_NOW: (SHORT: 'сада', LONG: 'управо сада'),
      SECONDS: (SHORT: 'с', LONG: 'секунда'),
      ONE_MINUTE: (SHORT: 'м', LONG: 'минут'),
      MINUTES: (SHORT: 'м', LONG: 'минута'),
      ONE_HOUR: (SHORT: 'с', LONG: 'сат'),
      HOURS: (SHORT: 'с', LONG: 'сата'),
      ONE_DAY: (SHORT: 'д', LONG: 'дан'),
      DAYS: (SHORT: 'д', LONG: 'дана'),
      ONE_MONTH: (SHORT: 'мес', LONG: 'месец'),
      MONTHS: (SHORT: 'мес', LONG: 'месеци'),
      SUFFIX: (SHORT: 'назад', LONG: 'назад'),
      ONE_YEAR: (SHORT: 'г', LONG: 'година'),
      YEARS: (SHORT: 'г', LONG: 'година'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'sr_Latn': TimeagoSymbol(
      JUST_NOW: (SHORT: 'sada', LONG: 'upravo sada'),
      SECONDS: (SHORT: 's', LONG: 'sekunda'),
      ONE_MINUTE: (SHORT: 'm', LONG: 'minut'),
      MINUTES: (SHORT: 'm', LONG: 'minuta'),
      ONE_HOUR: (SHORT: 's', LONG: 'sat'),
      HOURS: (SHORT: 's', LONG: 'sata'),
      ONE_DAY: (SHORT: 'd', LONG: 'dan'),
      DAYS: (SHORT: 'd', LONG: 'dana'),
      ONE_MONTH: (SHORT: 'mes', LONG: 'mesec'),
      MONTHS: (SHORT: 'mes', LONG: 'meseci'),
      SUFFIX: (SHORT: 'ranije', LONG: 'ranije'),
      ONE_YEAR: (SHORT: 'god', LONG: 'godina'),
      YEARS: (SHORT: 'god', LONG: 'godina'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'sv': TimeagoSymbol(
      JUST_NOW: (SHORT: 'nu', LONG: 'precis nu'),
      SECONDS: (SHORT: 's', LONG: 'sekund'),
      ONE_MINUTE: (SHORT: 'm', LONG: 'minut'),
      MINUTES: (SHORT: 'm', LONG: 'minuter'),
      ONE_HOUR: (SHORT: 'h', LONG: 'timme'),
      HOURS: (SHORT: 'h', LONG: 'timmar'),
      ONE_DAY: (SHORT: 'd', LONG: 'dag'),
      DAYS: (SHORT: 'd', LONG: 'dagar'),
      ONE_MONTH: (SHORT: 'mån', LONG: 'månad'),
      MONTHS: (SHORT: 'mån', LONG: 'månader'),
      SUFFIX: (SHORT: 'sedan', LONG: 'sedan'),
      ONE_YEAR: (SHORT: 'år', LONG: 'år'),
      YEARS: (SHORT: 'år', LONG: 'år'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'sw': TimeagoSymbol(
      JUST_NOW: (SHORT: 'sasa', LONG: 'sasa hivi'),
      SECONDS: (SHORT: 's', LONG: 'sekunde'),
      ONE_MINUTE: (SHORT: 'd', LONG: 'dakika'),
      MINUTES: (SHORT: 'd', LONG: 'dakika'),
      ONE_HOUR: (SHORT: 'h', LONG: 'saa'),
      HOURS: (SHORT: 'h', LONG: 'masaa'),
      ONE_DAY: (SHORT: 's', LONG: 'siku'),
      DAYS: (SHORT: 's', LONG: 'masiku'),
      ONE_MONTH: (SHORT: 'mwez', LONG: 'mwezi'),
      MONTHS: (SHORT: 'miezi', LONG: 'miezi'),
      SUFFIX: (SHORT: 'iliyopita', LONG: 'iliyopita'),
      ONE_YEAR: (SHORT: 'm', LONG: 'mwaka'),
      YEARS: (SHORT: 'miaka', LONG: 'miaka'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'ta': TimeagoSymbol(
      JUST_NOW: (SHORT: 'இப்போது', LONG: 'இப்போது'),
      SECONDS: (SHORT: 'வினா', LONG: 'வினாடி'),
      ONE_MINUTE: (SHORT: 'நி', LONG: 'நிமிடம்'),
      MINUTES: (SHORT: 'நி', LONG: 'நிமிடங்கள்'),
      ONE_HOUR: (SHORT: 'மணி', LONG: 'மணி'),
      HOURS: (SHORT: 'மணி', LONG: 'மணிகள்'),
      ONE_DAY: (SHORT: 'நா', LONG: 'நாள்'),
      DAYS: (SHORT: 'நா', LONG: 'நாட்கள்'),
      ONE_MONTH: (SHORT: 'மா', LONG: 'மாதம்'),
      MONTHS: (SHORT: 'மா', LONG: 'மாதங்கள்'),
      SUFFIX: (SHORT: 'முன்னர்', LONG: 'முன்னர்'),
      ONE_YEAR: (SHORT: 'வருடம்', LONG: 'வருடம்'),
      YEARS: (SHORT: 'வருடங்கள்', LONG: 'வருடங்கள்'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'te': TimeagoSymbol(
      JUST_NOW: (SHORT: 'ఇప్పుడు', LONG: 'ఇప్పుడు'),
      SECONDS: (SHORT: 'సె', LONG: 'సెకనులు'),
      ONE_MINUTE: (SHORT: 'ని', LONG: 'నిమిషం'),
      MINUTES: (SHORT: 'ని', LONG: 'నిమిషాలు'),
      ONE_HOUR: (SHORT: 'గం', LONG: 'గంట'),
      HOURS: (SHORT: 'గం', LONG: 'గంటలు'),
      ONE_DAY: (SHORT: 'రో', LONG: 'రోజు'),
      DAYS: (SHORT: 'రో', LONG: 'రోజులు'),
      ONE_MONTH: (SHORT: 'నె', LONG: 'నెల'),
      MONTHS: (SHORT: 'నె', LONG: 'నెలలు'),
      SUFFIX: (SHORT: 'క్రితం', LONG: 'క్రితం'),
      ONE_YEAR: (SHORT: 'సంవ', LONG: 'సంవత్సరం'),
      YEARS: (SHORT: 'సంవ', LONG: 'సంవత్సరాలు'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'th': TimeagoSymbol(
      JUST_NOW: (SHORT: 'เดี๋ยวนี้', LONG: 'เดี๋ยวนี้'),
      SECONDS: (SHORT: 'วิ', LONG: 'วินาที'),
      ONE_MINUTE: (SHORT: 'นาที', LONG: 'นาที'),
      MINUTES: (SHORT: 'นาที', LONG: 'นาที'),
      ONE_HOUR: (SHORT: 'ชม', LONG: 'ชั่วโมง'),
      HOURS: (SHORT: 'ชม', LONG: 'ชั่วโมง'),
      ONE_DAY: (SHORT: 'วัน', LONG: 'วัน'),
      DAYS: (SHORT: 'วัน', LONG: 'วัน'),
      ONE_MONTH: (SHORT: 'เดือน', LONG: 'เดือน'),
      MONTHS: (SHORT: 'เดือน', LONG: 'เดือน'),
      SUFFIX: (SHORT: 'ที่ผ่านมา', LONG: 'ที่ผ่านมา'),
      ONE_YEAR: (SHORT: 'ปี', LONG: 'ปี'),
      YEARS: (SHORT: 'ปี', LONG: 'ปี'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'tl': TimeagoSymbol(
      JUST_NOW: (SHORT: 'ngayon', LONG: 'ngayon lang'),
      SECONDS: (SHORT: 's', LONG: 'segundo'),
      ONE_MINUTE: (SHORT: 'm', LONG: 'minuto'),
      MINUTES: (SHORT: 'm', LONG: 'minuto'),
      ONE_HOUR: (SHORT: 'o', LONG: 'oras'),
      HOURS: (SHORT: 'o', LONG: 'oras'),
      ONE_DAY: (SHORT: 'a', LONG: 'araw'),
      DAYS: (SHORT: 'a', LONG: 'araw'),
      ONE_MONTH: (SHORT: 'b', LONG: 'buwan'),
      MONTHS: (SHORT: 'b', LONG: 'buwan'),
      SUFFIX: (SHORT: 'na ang nakalipas', LONG: 'na ang nakalipas'),
      ONE_YEAR: (SHORT: 't', LONG: 'taon'),
      YEARS: (SHORT: 't', LONG: 'taon'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'tr': TimeagoSymbol(
      JUST_NOW: (SHORT: 'şimdi', LONG: 'şu anda'),
      SECONDS: (SHORT: 's', LONG: 'saniye'),
      ONE_MINUTE: (SHORT: 'd', LONG: 'dakika'),
      MINUTES: (SHORT: 'd', LONG: 'dakika'),
      ONE_HOUR: (SHORT: 's', LONG: 'saat'),
      HOURS: (SHORT: 's', LONG: 'saat'),
      ONE_DAY: (SHORT: 'g', LONG: 'gün'),
      DAYS: (SHORT: 'g', LONG: 'gün'),
      ONE_MONTH: (SHORT: 'a', LONG: 'ay'),
      MONTHS: (SHORT: 'a', LONG: 'ay'),
      SUFFIX: (SHORT: 'önce', LONG: 'önce'),
      ONE_YEAR: (SHORT: 'y', LONG: 'yıl'),
      YEARS: (SHORT: 'y', LONG: 'yıl'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'zh_CN': TimeagoSymbol(
        JUST_NOW: (SHORT: '刚刚', LONG: '刚刚'),
        SECONDS: (SHORT: '秒', LONG: '秒'),
        ONE_MINUTE: (SHORT: '1分钟', LONG: '1分钟'),
        MINUTES: (SHORT: '分钟', LONG: '分钟'),
        ONE_HOUR: (SHORT: '1小时', LONG: '1小时'),
        HOURS: (SHORT: '小时', LONG: '小时'),
        ONE_DAY: (SHORT: '1天', LONG: '1天'),
        DAYS: (SHORT: '天', LONG: '天'),
        ONE_MONTH: (SHORT: '1个月', LONG: '1个月'),
        MONTHS: (SHORT: '个月', LONG: '个月'),
        ONE_YEAR: (SHORT: '1年', LONG: '1年'),
        YEARS: (SHORT: '年', LONG: '年'),
        SUFFIX: (SHORT: '前', LONG: '前'),
        SEPARATOR: (SHORT: ' ', LONG: ' ')),
    'zh_HK': TimeagoSymbol(
        JUST_NOW: (SHORT: '啱啱', LONG: '啱啱'),
        SECONDS: (SHORT: '秒', LONG: '秒'),
        ONE_MINUTE: (SHORT: '1分鐘', LONG: '1分鐘'),
        MINUTES: (SHORT: '分鐘', LONG: '分鐘'),
        ONE_HOUR: (SHORT: '1小時', LONG: '1小時'),
        HOURS: (SHORT: '小時', LONG: '小時'),
        ONE_DAY: (SHORT: '1日', LONG: '1日'),
        DAYS: (SHORT: '日', LONG: '日'),
        ONE_MONTH: (SHORT: '1個月', LONG: '1個月'),
        MONTHS: (SHORT: '個月', LONG: '個月'),
        ONE_YEAR: (SHORT: '1年', LONG: '1年'),
        YEARS: (SHORT: '年', LONG: '年'),
        SUFFIX: (SHORT: '前', LONG: '前'),
        SEPARATOR: (SHORT: ' ', LONG: ' ')),
    'zh_TW': TimeagoSymbol(
        JUST_NOW: (SHORT: '剛剛', LONG: '剛剛'),
        SECONDS: (SHORT: '秒', LONG: '秒'),
        ONE_MINUTE: (SHORT: '1分鐘', LONG: '1分鐘'),
        MINUTES: (SHORT: '分鐘', LONG: '分鐘'),
        ONE_HOUR: (SHORT: '1小時', LONG: '1小時'),
        HOURS: (SHORT: '小時', LONG: '小時'),
        ONE_DAY: (SHORT: '1天', LONG: '1天'),
        DAYS: (SHORT: '天', LONG: '天'),
        ONE_MONTH: (SHORT: '1個月', LONG: '1個月'),
        MONTHS: (SHORT: '個月', LONG: '個月'),
        ONE_YEAR: (SHORT: '1年', LONG: '1年'),
        YEARS: (SHORT: '年', LONG: '年'),
        SUFFIX: (SHORT: '前', LONG: '前'),
        SEPARATOR: (SHORT: ' ', LONG: ' ')),
    'zu': TimeagoSymbol(
        JUST_NOW: (SHORT: 'manje', LONG: 'manje nje'),
        SECONDS: (SHORT: 'amasekondi', LONG: 'amasekondi embalwa'),
        ONE_MINUTE: (SHORT: 'mzuz', LONG: 'umzuz omnye'),
        MINUTES: (SHORT: 'imizuz', LONG: 'imizuz'),
        ONE_HOUR: (SHORT: 'ihora', LONG: 'ihora eyodwa'),
        HOURS: (SHORT: 'amahora', LONG: 'amahora'),
        ONE_DAY: (SHORT: 'usuku', LONG: 'usuku lunye'),
        DAYS: (SHORT: 'izinsuku', LONG: 'izinsuku'),
        ONE_MONTH: (SHORT: 'inyanga', LONG: 'inyanga eyodwa'),
        MONTHS: (SHORT: 'izinyanga', LONG: 'izinyanga'),
        ONE_YEAR: (SHORT: 'umnyaka', LONG: 'umnyaka owodwa'),
        YEARS: (SHORT: 'iminyaka', LONG: 'iminyaka'),
        SUFFIX: (SHORT: 'edlule', LONG: 'edlule'),
        SEPARATOR: (SHORT: ' ', LONG: ' ')),
    'uk': TimeagoSymbol(
      JUST_NOW: (SHORT: 'зараз', LONG: 'зараз'),
      SECONDS: (SHORT: 'с', LONG: 'секунда'),
      ONE_MINUTE: (SHORT: 'х', LONG: 'хвилина'),
      MINUTES: (SHORT: 'хв', LONG: 'хвилини'),
      ONE_HOUR: (SHORT: 'г', LONG: 'година'),
      HOURS: (SHORT: 'г', LONG: 'години'),
      ONE_DAY: (SHORT: 'д', LONG: 'день'),
      DAYS: (SHORT: 'д', LONG: 'дні'),
      ONE_MONTH: (SHORT: 'м', LONG: 'місяць'),
      MONTHS: (SHORT: 'м', LONG: 'місяці'),
      SUFFIX: (SHORT: 'тому', LONG: 'тому'),
      ONE_YEAR: (SHORT: 'р', LONG: 'рік'),
      YEARS: (SHORT: 'р', LONG: 'роки'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'ur': TimeagoSymbol(
      JUST_NOW: (SHORT: 'ابھی', LONG: 'ابھی ابھی'),
      SECONDS: (SHORT: 'سیکنڈ', LONG: 'سیکنڈ'),
      ONE_MINUTE: (SHORT: 'منٹ', LONG: 'منٹ'),
      MINUTES: (SHORT: 'منٹ', LONG: 'منٹس'),
      ONE_HOUR: (SHORT: 'گھنٹہ', LONG: 'گھنٹے'),
      HOURS: (SHORT: 'گھنٹے', LONG: 'گھنٹے'),
      ONE_DAY: (SHORT: 'دن', LONG: 'دن'),
      DAYS: (SHORT: 'دن', LONG: 'دن'),
      ONE_MONTH: (SHORT: 'مہینہ', LONG: 'مہینے'),
      MONTHS: (SHORT: 'مہینے', LONG: 'مہینے'),
      SUFFIX: (SHORT: 'پہلے', LONG: 'پہلے'),
      ONE_YEAR: (SHORT: 'سال', LONG: 'سال'),
      YEARS: (SHORT: 'سال', LONG: 'سال'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'uz': TimeagoSymbol(
      JUST_NOW: (SHORT: 'hozir', LONG: 'hozir'),
      SECONDS: (SHORT: 'soniya', LONG: 'soniya'),
      ONE_MINUTE: (SHORT: 'daqiqa', LONG: 'daqiqa'),
      MINUTES: (SHORT: 'daqiqa', LONG: 'daqiqalar'),
      ONE_HOUR: (SHORT: 'soat', LONG: 'soat'),
      HOURS: (SHORT: 'soat', LONG: 'soatlar'),
      ONE_DAY: (SHORT: 'kun', LONG: 'kun'),
      DAYS: (SHORT: 'kun', LONG: 'kunlar'),
      ONE_MONTH: (SHORT: 'oy', LONG: 'oy'),
      MONTHS: (SHORT: 'oy', LONG: 'oylar'),
      SUFFIX: (SHORT: 'avval', LONG: 'avval'),
      ONE_YEAR: (SHORT: 'yil', LONG: 'yil'),
      YEARS: (SHORT: 'yil', LONG: 'yillar'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'vi': TimeagoSymbol(
      JUST_NOW: (SHORT: 'ngay lập tức', LONG: 'ngay lập tức'),
      SECONDS: (SHORT: 'giây', LONG: 'giây'),
      ONE_MINUTE: (SHORT: 'phút', LONG: 'phút'),
      MINUTES: (SHORT: 'phút', LONG: 'phút'),
      ONE_HOUR: (SHORT: 'giờ', LONG: 'giờ'),
      HOURS: (SHORT: 'giờ', LONG: 'giờ'),
      ONE_DAY: (SHORT: 'ngày', LONG: 'ngày'),
      DAYS: (SHORT: 'ngày', LONG: 'ngày'),
      ONE_MONTH: (SHORT: 'tháng', LONG: 'tháng'),
      MONTHS: (SHORT: 'tháng', LONG: 'tháng'),
      SUFFIX: (SHORT: 'trước', LONG: 'trước'),
      ONE_YEAR: (SHORT: 'năm', LONG: 'năm'),
      YEARS: (SHORT: 'năm', LONG: 'năm'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
    'zh': TimeagoSymbol(
      JUST_NOW: (SHORT: '刚刚', LONG: '刚刚'),
      SECONDS: (SHORT: '秒', LONG: '秒'),
      ONE_MINUTE: (SHORT: '分钟', LONG: '分钟'),
      MINUTES: (SHORT: '分钟', LONG: '分钟'),
      ONE_HOUR: (SHORT: '小时', LONG: '小时'),
      HOURS: (SHORT: '小时', LONG: '小时'),
      ONE_DAY: (SHORT: '天', LONG: '天'),
      DAYS: (SHORT: '天', LONG: '天'),
      ONE_MONTH: (SHORT: '个月', LONG: '个月'),
      MONTHS: (SHORT: '个月', LONG: '个月'),
      SUFFIX: (SHORT: '前', LONG: '前'),
      ONE_YEAR: (SHORT: '年', LONG: '年'),
      YEARS: (SHORT: '年', LONG: '年'),
      SEPARATOR: (SHORT: '', LONG: ' '),
    ),
  };
}
